
lecture_12 <- function() {
  
  init <- tar_plan(
    path12 = "figures/12_multiple_test_corrections"
  )

  read_data <- tar_plan(
    # this are tweaked p-values generated by Perl script
    two_data_p = read_two_p("data/multi_two_hypotheses.txt"),
    two_data_p_fdr = read_two_p("data/multi_point_FDR.txt")
  )
  
  comp <- tar_plan(
    small_p_data = make_small_p_data(),
    large_p_data = make_large_p_data(two_data_p),
    
    fdr_dist = generate_fdr_distribution()
  )
  
  make_figures <- tar_plan(
    # FWER
    figs_fwer = plot_fwer(),
    s_fw_1 = gs(figs_fwer$fwer, path12, 3.5, 3),
    s_fw_2 = gs(figs_fwer$fwer_bonferroni, path12, 3.5, 3),
    
    # test data
    s_td2 = plot_two_dist() |> gs(path12, 4, 4, "test_data_dist"),
    s_tp2 = plot_two_dist_p(two_data_p) |> gs(path12, 3.5, 3, "test_data_dist_pvalue"),
    
    # HM = BH
    figs_small_dat = plot_small_data(small_p_data),
    s_shb = gs(figs_small_dat$holm_bonferroni, path12, 3, 2.5),
    s_sbh = gs(figs_small_dat$benjamini_hochberg, path12, 3, 2.5),
    
    figs_large_dat = plot_large_data(large_p_data),
    s_lb_1 = gs(figs_large_dat$large_HB, path12, 4, 3.5),
    s_lb_2 = gs(figs_large_dat$large_BH, path12, 4, 3.5),
    s_lb_3 = gs(figs_large_dat$large_adjusted, path12, 4, 3.5),
    
    # FDR
    s_fdr = plot_fdr_distribution(fdr_dist) |> gs(path12, 3, 3, "fdr_dist"),
    
    # p distributions
    figs_pdist = plot_p_distributions(),
    s_pd_1 = gs(figs_pdist$p_dist_null, path12, 3.5, 2.5),
    s_pd_2 = gs(figs_pdist$p_dist_alt, path12, 3.5, 2.5),
    s_pd_3 = gs(figs_pdist$p_dist_bad, path12, 3.5, 2.5),
    s_pd_4 = gs(figs_pdist$p_dist_alt_one, path12, 3.5, 2.5),
    s_pd_5 = gs(figs_pdist$p_dist_alt_p, path12, 3.5, 2.5),
    
    # Storey method
    figs_storey = plot_storey(two_data_p_fdr),
    s_fs_1 = gs(figs_storey$pq_bh, path12, 3.5, 3),
    s_fs_2 = gs(figs_storey$pq, path12, 4, 3.5),
    s_fs_3 = gs(figs_storey$pq_small, path12, 2, 2),
    s_fs_4 = gpl(figs_storey$pq_hist, path12, 5, 4)
  )
  
  make_tables <- tar_plan(
    tab_no_correction = p_table(two_data_p, alpha = 0.05),
    tab_bonferroni = p_table(two_data_p, alpha = 0.00005),
    tab_benjamini_hochberg = p_table(two_data_p, alpha = 0.05, what = "padj")
  )

  
  c(
    init,
    comp,
    read_data,
    make_figures,
    make_tables
  )
  
  
}
