---
title: "Why do we need statistics"
output: html_document
params: 
  output_dir: "../output"
---

```{r setup, echo=FALSE}
root <- "00_why_statistics"
source("../R/setup.R")
library(beeswarm)
library(tidyverse)
library(edgeR)
library(ggforce)
knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  echo = FALSE,
  cache = TRUE,
  cache.path = paste0("../cache/", root),
  fig.path = paste0("../cache/", root)
)
options(width=200)
fig <- paste0("../fig/", root, "/")
if(!dir.exists(fig)) dir.create(fig)

select <- dplyr::select
```

```{css echo=FALSE}
pre code, pre, code {
  white-space: pre !important;
  overflow-x: scroll !important;
  word-break: keep-all !important;
  word-wrap: initial !important;
}
```




```{r read_grna}
X1 <- read.table("../data/WT_lev.tsv", sep="\t")
gene.id <- X1[, 1]
X1 <- X1[, -1]
colnames(X1) <- paste0("WT_", 1:ncol(X1))
X1 <- X1[, -c(21,22,25,28,34,36)]
X2 <- read.table("../data/Snf2_lev.tsv", sep="\t")
X2 <- X2[, -1]
colnames(X2) <- paste0("Snf2_", 1:ncol(X2))
X2 <- X2[, -c(6,13,25,35)]
grna <- data.frame(X1, X2)
rownames(grna) <- gene.id
```



```{r grna_gene, fig.width=3, fig.height=3}
plotGene <- function(gene, sel=NULL, p.alpha=1) {
  m <- melt(grna[gene,])
  lims <- c(min(m$value), max(m$value))
  if(!is.null(sel)) m <- m[m$variable %in% sel,]
  m$condition <- as.factor(gsub("_\\d+", "", m$variable, perl=TRUE))
  m$condition <- relevel(m$condition, "WT")
  if(is.null(sel)) print(t.test(value~condition, data=m))
  
  mm <- m %>% group_by(condition) %>% summarise(M=mean(value), SD=sd(value), n=n()) %>% mutate(CI = SD/sqrt(n) * qt(0.975, n - 1))
  print(mm)
  mm$i <- c(1.3, 1.7)
  
  g <- ggplot() +
    theme_classic() +
    #geom_boxplot(alpha=0.3, colour="grey70", outlier.shape = NA) +
    scale_fill_manual(values=cbPalette, guide=FALSE) +
    geom_beeswarm(data=m, aes(x=condition, y=value, fill=condition), cex=3, size=1, shape=21, priority="density", alpha=p.alpha) +
    labs(x=NULL, y="Read count") +
    scale_x_discrete(labels=c("WT", expression(Delta*Snf2))) +
    ylim(lims)
  if(is.null(sel)) {
    g <- g +
      geom_errorbar(data=mm, aes(x=i, ymin=M-CI, ymax=M+CI), width=0.15) +
      geom_point(data=mm, aes(x=i, y=M, fill=condition), size=3, shape=22)
  }
  g
}

gene <- "yfr017c"
sort(grna[gene, ])

g1 <- plotGene(gene)
g1

g2 <- plotGene(gene, p.alpha=0.3)
g2

ggsave(paste0(fig, "grna_expression_1.png"), plot=g1, device="png", width=2.1, height=3.5, dpi=300) 
ggsave(paste0(fig, "grna_expression_2.png"), plot=g2, device="png", width=2.6, height=3.5, dpi=300) 
```


```{r poisson_plates}
set.seed(223)
p <- rnbinom(8, mu=20, size=5)
p <- c(10, 30, p)
d <- data.frame(plate=seq_along(p), cnt = p)

g1 <- ggplot(d, aes(plate, cnt)) +
  theme_classic() +
  theme(panel.grid.major.y = element_line(colour="grey80")) +
  #geom_segment(aes(x=plate, xend=plate, y=cnt, yend=0), colour="grey80") +
  geom_point(shape=22, fill=fill.colour) +
  scale_x_continuous(breaks=1:10) +
  scale_y_continuous(expand=c(0,0), limits=c(0, max(p) * 1.3)) +
  labs(x="Plate", y="Count")
g1
ggsave(paste0(fig, "poisson_plates.png"), plot=g1, device="png", width=3, height=3, dpi=300)
```

```{r body_temperature}
# data from Shoemaker A. L.,  College C., Journal of Statistics Education 4 (1996)
body <- read.table("../data/normtemp.dat.txt", header=FALSE)
names(body) <- c("temperature.f", "sex", "hrate")
body$temperature.c <- (body$temperature.f - 32) *5 / 9

M <- mean(body$temperature.c)
S <- sd(body$temperature.c)
x <- seq(35,39,0.01)
m <- data.frame(
  x = x,
  y = dnorm(x, mean=M, sd=S)
)

g1 <- ggplot(body, aes(x=temperature.c, y=1)) +
  theme_classic() +
  theme(
    axis.title.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.text.y = element_blank(),
    plot.margin = margin(t=-2,r=6,l=3)
  ) +
  geom_beeswarm(groupOnX = FALSE, cex=1, size=0.8, shape=21, fill=fill.colour) +
  scale_x_continuous(expand=c(0,0), limits=c(35, 39)) +
  scale_y_continuous(expand=c(0.1,0)) +
  labs(x=expression(Body~temperature~(degree*C)))
  
brks <- seq(35,39,0.2)
g2 <- ggplot() +
  theme_classic() +
  theme(
    axis.title.x = element_blank(),
    axis.ticks.x = element_blank(),
    axis.text.x = element_blank(),
    plot.margin = margin(b=0,r=6,t=10,l=3)
  ) +
  geom_histogram(data=body, aes(x=temperature.c, y=..density..), breaks=brks, fill=fill.colour) +
  geom_outline(body$temperature.c, breaks=brks) +
  geom_line(data=m, aes(x,y), colour="brown3") +
  scale_y_continuous(expand=c(0,0), limits=c(0,1.2), breaks=seq(0.2,1.2,0.2)) +
  scale_x_continuous(expand=c(0,0), limits=c(35, 39)) +
  labs(x=NULL, y="Density")


g <- plot_grid(g2, g1, ncol=1, align="v", rel_heights = c(3,1))
g
ggsave(paste0(fig, "body_temp.png"), plot=g, device="png", width=3.5, height=3.5, dpi=300)

```


```{r tumour_growth_read_data}
ptpn <- read_tsv("../data/tumour_ptpn.txt", name_repair = make.names) %>%
  setNames(c("day", paste0("KO_", 1:12), paste0("WT_", 1:12), "day")) %>% 
  mutate(day = as.numeric(gsub("day", "", day))) %>%
  gather("sample", "volume", -day) %>%
  separate("sample", c("condition", "replicate"), "_", remove=FALSE) %>%
  filter(!is.na(volume) & volume > 0) %>%
  mutate(lvolume = log10(volume), lday=log10(day))

m <- ptpn %>%
  group_by(condition, day) %>%
  summarise(M = mean(volume), SE = sd(volume) / sqrt(n()))
```


```{r plot_tumour_lines, fig.width=8}
y.lims <- c(0.3, 1300)
d.brks <- 1:21
d.labs <- rep("", length(d.brks))
d.labs[c(5, 10, 20)] <- c(5, 10, 20)
t.size <- 9

g1 <- ggplot(ptpn, aes(x=day, y=volume, group=sample, colour=condition)) +
    theme_classic() +
    geom_line() +
    labs(x="Day", y=expression(Tumor~volume~(mm^3)), title="Raw data") +
    scale_x_log10() +
    scale_y_log10(expand=c(0,0), limits=y.lims) +
    scale_colour_manual(values=cbPalette, guide=FALSE) +
    theme(plot.title=element_text(size=t.size))

g2 <- ggplot(m) +
  theme_classic() +
  geom_line(aes(x=day, y=M, colour=condition)) +
  geom_ribbon(aes(x=day, ymin=M-SE, ymax=M+SE, fill=condition), alpha=0.3) +
  scale_x_log10() +
  scale_y_log10(expand=c(0,0), limits=y.lims) +
  scale_colour_manual(values=cbPalette, guide=FALSE) +
  scale_fill_manual(values=cbPalette, guide=FALSE) +
  labs(x="Day", y=NULL, title="Mean and standard error") +
  theme(plot.title=element_text(size=t.size))


g3 <- ggplot(ptpn, aes(x=lday, y=lvolume, colour=condition)) +
  theme_classic() +
  theme(
    legend.key = element_rect(fill="white", colour=NA),
    legend.text = element_text(size=8),
    legend.title = element_text(size=9),
    plot.title = element_text(size=t.size)
  ) +
  geom_point(size=0.5, alpha=0.4) +
  stat_smooth(method="lm") +
  scale_colour_manual(values=cbPalette) +
  labs(x="Day", y=NULL, title="Linear model") +
  scale_x_continuous(breaks=log10(c(5,10,20)), labels=c(5,10,20)) +
  scale_y_continuous(breaks=c(0,1,2,3), labels=c(1,10,100,1000), expand=c(0,0), limits=log10(y.lims)) +
  guides(color=guide_legend(override.aes=list(fill=NA)))


g <- plot_grid(g1, g2, g3, nrow=1, rel_widths = c(1.05, 0.9, 1.3))
g

ggsave(paste0(fig, "tumour_growth.png"), plot=g, device="png", width=7, height=3, dpi=300)

```


```{r read_devspine}
conditions <- c("E12.5", "E16.5", "Adult")
replicates <- 1:3
metadata <- expand.grid(replicate=replicates, condition=conditions) %>%
  unite(sample, c(condition, replicate), sep="-", remove=FALSE) %>%
  mutate(column = tolower(sample)) %>% 
  mutate(column = gsub("\\.", "", column)) %>%
  mutate(column = gsub("-", "_", column))

ds <- 
  read_tsv("../data/expr_e125-e165-adult_raw.tsv") %>%
  filter(rowSums(.[2:10]) > 0) %>%
  filter(str_detect(GeneID, pattern="ensmusg")) %>%
  column_to_rownames("GeneID") %>%
  setNames(metadata$sample)

norms <- as.matrix(ds) %>%
  DGEList(group=metadata$condition) %>%
  calcNormFactors() %>%
  pluck("samples", "norm.factors")

dsn <- t(t(ds) * norms) %>% as.data.frame


ds2 <- ds[, c(1:3, 7:9)]
dsn2 <- dsn[, c(1:3, 7:9)]

dim(ds)
```

```{r clustering function}
plotClustering_ <- function(cnt, x.text.size=10) {
  corr.mat <- cor(cnt, use="complete.obs")
  dis <- as.dist(1 - corr.mat)  # dissimilarity matrix
  hc <- hclust(dis)
  dendr <- ggdendro::dendro_data(hc)
  dat <- ggdendro::segment(dendr)
  lab <- dendr$labels %>% mutate(condition = gsub("-\\d", "", label, perl=TRUE))
  theme.d <- ggplot2::theme(
    panel.grid.major = ggplot2::element_blank(),
    panel.grid.minor = ggplot2::element_blank(),
    panel.background = ggplot2::element_blank(),
    axis.text.y = element_blank(),
    axis.line.y = ggplot2::element_blank(),
    axis.line.x = ggplot2::element_line(size=0.5),
    axis.ticks.y = ggplot2::element_blank(),
    legend.position = "none"
  )
  ggplot() +
    theme.d +
    geom_segment(data=dat, aes_(x=~x, y=~y, xend=~xend, yend=~yend)) +
    geom_text(data=lab, aes(x=x, y=y, label=label, colour=condition), hjust=1) +
    coord_flip() +
    #scale_x_continuous(breaks = seq_along(dendr$labels$label), labels = dendr$labels$label) +
    scale_y_continuous(expand = c(0.2,0), limits = c(0, max(dat$y) * 1.03)) +
    labs(x=NULL, y="Distance")
}

library(dendextend)
plotClustering <- function(cnt) {
  corr.mat <- cor(cnt, use = "complete.obs") 
  dend <- as.dist(1 - corr.mat) %>% hclust %>% as.dendrogram
  cond <- gsub("-\\d", "", colnames(cnt), perl=TRUE) %>%
    factor(levels=c("E12.5", "E16.5", "Adult")) %>%
    as.numeric
  cond <- cond[order.dendrogram(dend)]
  labels_colors(dend) <- cbPalette[cond]
  dend <- dend %>% set("labels_cex", 0.6) %>% set("branches_lwd", 0.3)
  gg <- as.ggdend(dend)
  ggplot(gg, horiz=FALSE, offset_labels=-0.01) + ylim(-0.1, max(get_branches_heights(dend)))
}

```

```{r clustering}
g <- plotClustering(ds)
g 
 
ggsave(paste0(fig, "clustering.png"), plot=g, device="png", width=3, height=3.5, dpi=300)

myKable(head(ds))

head(ds)
tail(ds,1)
```

```{r pairs, eval=FALSE}
ds %>% 
  filter(apply(ds, 1, max) > 10) %>% 
  as.matrix %>% log10 %>% as_tibble %>% 
ggplot(aes(x = .panel_x, y = .panel_y)) +
  geom_point(shape=16, size=0.5, alpha=0.5, position="auto") +
  geom_autodensity(alpha=0.3, colour=NA, position="identity") +
  facet_matrix(vars(everything()), layer.diag=2, grid.y.diag=FALSE) 
```

```{r distance_matrix}
plotDistanceMatrix <- function(cnt, metadata, distance=c("correlation"), text.size=10) {
  distance <- match.arg(distance)
  
  corr.mat <- cor(cnt, use="complete.obs")
  m <- reshape2::melt(corr.mat, varnames=c("Sample1", "Sample2"))
  m$Sample1 <- factor(m$Sample1, levels=metadata$sample)
  m$Sample2 <- factor(m$Sample2, levels=metadata$sample)
  clr <- cbPalette[as.factor(metadata$condition)]
  ggplot(m, aes_(x=~Sample1, y=~Sample2)) +
    geom_tile(aes_(fill=~value)) +
    viridis::scale_fill_viridis(option="cividis") +
    theme(
      axis.text.x = element_text(angle = 90, hjust = 1, vjust=0.5, size=text.size, colour=clr),
      axis.text.y = element_text(size=text.size, colour=clr)
    ) +
    labs(x=NULL, y=NULL, fill="Correlation")
}

g <- plotDistanceMatrix(ds, metadata)
g
ggsave(paste0(fig, "correlation_matrix.png"), plot=g, device="png", width=4.5, height=3, dpi=300)

```


```{r biomart_function}
biomartGeneDownload <- function(mart) {
  df <- getBM(attributes = c(
    "chromosome_name",
    "start_position",
    "end_position",
    "strand",
    "gene_biotype",
    "ensembl_gene_id",
    "external_gene_name",
    "description"
  ), mart=mart)
  df <- dplyr::rename(df,
    chr = chromosome_name,
    start = start_position,
    end = end_position,
    gene_id = ensembl_gene_id,
    gene_name = external_gene_name
  )
}

library(biomaRt)
mart <- useEnsembl(biomart="ensembl", dataset="mmusculus_gene_ensembl", version=94)
genes <- biomartGeneDownload(mart)
gene.names <- setNames(genes$gene_name, tolower(genes$gene_id))
```


```{r plot_one_gene_function}
plotOneGene <- function(dat, gene) {
  d <- dat[gene, ] %>%
    gather(key="sample", value="count") %>%
    mutate(condition = gsub("-\\d", "", sample, perl=TRUE)) %>%
    mutate(condition = factor(condition, levels=c("E12.5", "E16.5", "Adult")))
  ggplot(d, aes(x=condition, y=count, fill=condition)) +
    theme_linedraw() +
    theme(legend.position = "none") +
    geom_beeswarm(shape=21, cex=3, size=1.8) +
    scale_y_continuous(expand=c(0,0), limits=c(0, max(d$count) * 1.05)) +
    scale_fill_manual(values=cbPalette) +
    labs(x=NULL, y="Count", title=gene.names[gene])
}
```

```{r genes}
gene.id <- c("ensmusg00000051951", "ensmusg00000009281","ensmusg00000013415")
for(gene in gene.id) {
  g <- plotOneGene(dsn, gene)
  print(g)
  ggsave(paste0(fig, paste0("gene_", gene,".png")), plot=g, device="png", width=2.5, height=2, dpi=300)  
}
```


```{r de}
cond2 <- droplevels(metadata$condition[c(1:3,7:9)])
design <- model.matrix(~0 + cond2)
colnames(design) <- levels(cond2)

gt.contrasts <- makeContrasts(
  "Adult-E12.5" = "Adult-E12.5",
  levels = design
)

de.edger <- as.matrix(ds2) %>%
  DGEList(group=cond2) %>%
  calcNormFactors() %>%
  estimateDisp(design=design) %>%
  glmQLFit(design=design) %>%
  glmQLFTest(contrast=gt.contrasts[, "Adult-E12.5"]) %>%
  topTags(n=1e6, adjust.method="BH", sort.by="none") %>%
  pluck("table")

test <- function(v) {
  x <- v[1:3]
  y <- v[4:6]
  if(sum(is.na(x)) > 1 | sum(is.na(y)) > 1) {
    return(NA)
  } else {
    return(t.test(x, y)$p.value)
  }
}

de.t <- dsn2 %>%
  na_if(0) %>%
  log10 %>%
  apply(., 1, test) %>%
  as.data.frame %>%
  setNames("P")

de <- merge(de.edger, de.t, by="row.names") %>% rename(gene_id = Row.names)
```


```{r de_selection}
only.t <- de %>% filter(P < 0.05 & PValue < 0.05 & FDR > 0.1 & logCPM > 2)
only.edger <- de %>% filter(P > 0.1 & FDR < 0.01 & logCPM > 2)

gene <- only.edger[5, "gene_id"]
g1 <- plotOneGene(dsn2, gene)
print(de[de$gene_id == gene, ])
g1
ggsave(paste0(fig, paste0("gene_edger.png")), plot=g1, device="png", width=2.5, height=2, dpi=300) 

gene <- only.t[5, "gene_id"]
g2 <- plotOneGene(dsn2, gene)
print(de[de$gene_id == gene, ])
g2
ggsave(paste0(fig, paste0("gene_t.png")), plot=g2, device="png", width=2.5, height=2, dpi=300) 
```


```{r genes_de, eval=FALSE}
gene.id <- c("ensmusg00000023011", "ensmusg00000031671", "ensmusg00000043614")
for(gene in gene.id) {
  g <- plotOneGene(dsn2, gene)
  print(de[de$gene_id == gene,])
  t.test(dsn2[gene, 1:3], dsn2[gene, 4:6]) %>% print
  print(g)
  ggsave(paste0(fig, paste0("gene2_", gene,".png")), plot=g, device="png", width=2.5, height=2, dpi=300)
} 
```


```{r drugpred_data}
drugs <- readRDS("../data/drugpred.rds") %>% 
  rename(`logVDss` = response)
coef.names <- readRDS("../data/coef_names.rds")
drugs %>% 
  dplyr::select(Name, `logVDss`, LogBB, `S+pH_Satd`, FAnion, `log MaxQ`, MOLECULAR_SPECIES, moka_ionState7.4, TerAmine_) %>% 
  head(10) %>% 
  myKable()
```

```{r drugpred_functions}
showModel <- function(mod, alpha=0.05) {
  summary(mod)$coefficients %>%
    as.data.frame %>%
    rownames_to_column(var="coefficient") %>%
    as_tibble %>% 
    mutate(coefficient = gsub("`", "", coefficient)) %>%
    filter(`Pr(>|t|)` < alpha) %>%
    arrange(`Pr(>|t|)`) %>% 
    left_join(coef.names, by="coefficient") %>% 
    mutate(value = ifelse(is.na(value), " ", value)) %>% 
    select(coefficient, variable, value, estimate = Estimate, t = `t value`, `p-value` = `Pr(>|t|)`)
}
```


```{r drugs_model}
mod <- lm(`logVDss` ~ ., data=drugs[, -1])
showModel(mod) %>% myKable(digits=3)
```