---
title: "Probability distributions"
output:
  html_document:
    css: tabbed_notebook.css
    fig_width: 3
    fig_height: 3
params: 
  output_dir: "../output"
---

```{r setup, echo=FALSE}
root <- "01_probability_distributions"
source("../R/setup.R")
library(beeswarm)
knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  echo = FALSE,
  cache = TRUE,
  cache.path = paste0("../cache/", root),
  fig.path = paste0("../cache/", root)
)
fig <- paste0("../fig/", root, "/")
if(!dir.exists(fig)) dir.create(fig)
```

```{css echo=FALSE}
pre code, pre, code {
  white-space: pre !important;
  overflow-x: scroll !important;
  word-break: keep-all !important;
  word-wrap: initial !important;
}
```


```{r flg_expression, fig.width=2.1, fig.height=3.5}
set.seed(111)
ctrl <- c(41723, 1000*rnorm(29, 32, 8))
trt <- c(19786, 1000*rnorm(29, 28, 6))
paste(mean(ctrl), se(ctrl))
paste(mean(trt), se(trt))

dat <- data.frame(
  Type = c(rep("Control", 30), rep("Treatment", 30)),
  Value = c(ctrl, trt)
)
t.test(Value ~ Type, data=dat)
g <- ggplot(dat, aes(x=Type, y=Value/1000, fill=Type)) +
  theme_classic() +
  theme(
    legend.position = "none"
  ) +
  geom_boxplot(alpha=0.3, outlier.shape = NA) +
  scale_fill_manual(values=cbPalette) +
  geom_beeswarm(cex=3, size=1, shape=21) +
  labs(x="", y="Intensity (x1000)")
g

ggsave(paste0(fig, "flg_expression.png"), plot=g, device="png", width=2.1, height=3.5, dpi=300) 
```

```{r two_dice, fig.width=3, fig.height=3}
dist <- data.frame(
  x = 2:12,
  n = c(1:6, 5:1)
)
dist$y <- dist$n / sum(dist$n)

g <- ggplot(dist, aes(x, y)) +
  theme_classic() +
  geom_segment(aes(x=x, y=y, xend=x, yend=0), colour="grey") +
  geom_point(shape=21, fill="white", colour="black") +
  geom_text(aes(label=n), nudge_y=0.01) +
  scale_x_continuous(breaks=2:12) +
  scale_y_continuous(expand=c(0,0), limits=c(0, max(dist$y)*1.1)) +
  labs(x = "Outcome", y = "Probability")
g

ggsave(paste0(fig, "two_dice.png"), plot=g, device="png", width=3, height=3, dpi=300) 
```

```{r discrete_example,  fig.width=4, fig.height=3}
x <- 0:12
y <- dpois(x, 4)
dist <- data.frame(
  x = x,
  y = y
)

dist.cut <- subset(dist, x > 4 & x < 8)
dist.cut
sum(dist.cut$y)

g <- ggplot(dist, aes(x, y)) +
  theme_classic() +
  geom_col(fill=fill.colour, colour="black", width=0.7, size=0.3) +
  geom_col(data=dist.cut, fill=fill.colour.dark, colour="black", width=0.7, size=0.3) +
  scale_x_continuous(breaks=0:12) +
  scale_y_continuous(expand=c(0,0), limits=c(0, max(dist$y)*1.1)) +
  labs(x = "k", y = "P(X = k)")
g

ggsave(paste0(fig, "pdist_discrete.png"), plot=g, device="png", width=3, height=2.2, dpi=300) 
```

```{r geom_cut_function}
geom_cut <- function(lo, up, FUN, ..., n=100, colour="black", fill=fill.colour.dark) {
  x <- lo + (0:(n - 1)) * (up - lo) / (n - 1)
  d <- data.frame(
    x = c(lo, x, up),
    y = c(0, FUN(x, ...), 0)
  )
  geom_polygon(data=d, aes(x, y), colour=colour, fill=fill)
}
```


```{r continuous_example}
dof <- 5

x <- seq(0, 30, 0.1)
y <- dchisq(x, dof)
dchi2 <- data.frame(x=x, y=y)

chi2cut <- 10
1 - pchisq(chi2cut, dof)

g <- ggplot() +
  theme_dist +
  geom_line(data=dchi2, aes(x, y), colour="black") +
  labs(x="x", y="f(x)") +
  scale_x_continuous(limits=c(0, 25), expand=c(0,0)) +
  scale_y_continuous(limits=c(0, max(dchi2$y) * 1.05), expand=c(0,0)) +
  #geom_polygon(data=df, aes(x, y), colour="black", fill=fill.colour.dark)
  geom_cut(chi2cut, 25, dchisq, dof)
g

ggsave(paste0(fig, "pdist_continuous.png"), plot=g, device="png", width=3, height=2.2, dpi=300)
```


```{r normal}
M <- 10
S <- 1.5

x <- seq(0, 20, 0.1)
y <- dnorm(x, M, S)
dn <- data.frame(x=x, y=y)

lns1 <- data.frame(
  x = c(M - S, M, M + S),
  y = c(0.3, 0.28, 0.3)
)

lns2 <- data.frame(
  x = c(M - 3*S, M - 2*S, M + 2*S, M + 3*S),
  y = c(0.4, 0.35, 0.35, 0.4)
)

g1 <- ggplot() +
  theme_dist +
  geom_segment(data=lns1, aes(x=x, y=y, xend=x, yend=0), colour="grey") +
  geom_line(data=dn, aes(x, y), colour="black") +
  labs(x="x", y="f(x)") +
  scale_x_continuous(limits=c(4, 16), expand=c(0,0)) +
  scale_y_continuous(limits=c(0, 0.4), expand=c(0,0))


g2 <- g1 + 
  geom_segment(data=lns2, aes(x=x, y=y, xend=x, yend=0), colour="grey") +
  geom_cut(M - 3*S, M + 3*S, dnorm, M, S, fill=fill.colour) +
  geom_cut(M - 2*S, M + 2*S, dnorm, M, S, fill=fill.colour.mid) +
  geom_cut(M - 1*S, M + 1*S, dnorm, M, S, fill=fill.colour.dark) 

g1
g2


ggsave(paste0(fig, "normal_example_1.png"), plot=g1, device="png", width=3, height=2.5, dpi=300)
ggsave(paste0(fig, "normal_example_2.png"), plot=g2, device="png", width=3, height=2.5, dpi=300)
```

```{r baseball_height}
bb <- read.table("../data/baseball.txt", header=TRUE, sep="\t", quote="")
bb$height <- 2.54 * bb$Height.inches.

tab <- table(bb$height)
d <- data.frame(
  x = as.numeric(names(tab)),
  y = as.integer(tab)
)
bins <- d$x[2] - d$x[1]

M <- mean(bb$height)
S <- sd(bb$height)
dim(bb)
M
S

xx <- seq(100, 250, 0.1)
m <- data.frame(
  x = xx,
  y = dnorm(xx, M, S) * sum(d$y) * bins
)

g <- ggplot(d, aes(x, y)) +
  geom_segment(aes(xend=x, yend=0), colour="grey60") +
  geom_point(shape=21, fill="white", size=2) +
  scale_y_continuous(expand=c(0,0), limits=c(0, max(d$y) * 1.03)) +
  geom_line(data=m, aes(x, y), colour="red") +
  labs(x = "Height (cm)", y = "Frequency") +
  scale_x_continuous(limits=c(165, 215), expand=c(0,0))

g

ggsave(paste0(fig, "baseball_height.png"), plot=g, device="png", width=5, height=4, dpi=300)
```


```{r lognormal_dist}
td <- read.table("../data/testdist.dat")
td$int <- td$V1 / 1e6
td$lint <- log10(td$V1)
M1 <- mean(td$int)
S1 <- sd(td$int)
M2 <- mean(td$lint)
S2 <- sd(td$lint)

M1
S1
M2
S2

g1 <- plotOneDist(td$int, expression(Intensity~x10^6), "Linear scale", c(0, 10), with.outline=TRUE, outline.colour="grey30", maxy=1.7) +
  scale_x_continuous(breaks=c(0,2,4,6,8,10), expand=c(0,0))
g1.1 <- g1 +
  geom_vline(xintercept = M1) + geom_vline(xintercept = M1+S1, linetype="dotted") + labs(title="")
g1
g1.1

g2 <- plotOneDist(td$lint, expression(log[10]~Intensity), "Logarithmic scale", c(3.5, 8.5), with.outline=TRUE, outline.colour="grey30", max=0.65)
g2.1 <- g2 +
  geom_vline(xintercept = M2) + geom_vline(xintercept = c(M2-S2, M2+S2), linetype="dotted") + labs(title="")
g2
g2.1

ggsave(paste0(fig, "lognormal_1.png"), plot=g1, device="png", width=3.5, height=3, dpi=300)
ggsave(paste0(fig, "lognormal_2.png"), plot=g2, device="png", width=3.5, height=3, dpi=300)
ggsave(paste0(fig, "lognormal_1.1.png"), plot=g1.1, device="png", width=3.5, height=3, dpi=300)
ggsave(paste0(fig, "lognormal_2.1.png"), plot=g2.1, device="png", width=3.5, height=3, dpi=300)
```

```{r lognormal_data}
d <- read.table("../data/slc7a5_read_counts.txt", sep="\t", header=TRUE)
mx <- max(c(d$wt.1, d$wt.2)) / 1e6

g1 <- ggplot(d, aes(wt.1/1e6, wt.2/1e6)) +
  theme_classic() +
  geom_point(alpha=0.2) +
  scale_x_continuous(expand=c(0,0), limits=c(0, mx*1.03)) +
  scale_y_continuous(expand=c(0,0), limits=c(0, mx*1.03)) +
  labs(x=expression(I[1]~(x10^6)), y=expression(I[2]~(x10^6)))
g1

g2 <- ggplot(d, aes(log10(wt.1+0.5), log10(wt.2+0.5))) +
  theme_classic() +
  geom_point(alpha=0.2) +
  scale_x_continuous(expand=c(0,0), limits=c(-0.8, 6)) +
  scale_y_continuous(expand=c(0,0), limits=c(-0.8, 6)) +
  labs(x=expression(log[10]~I[1]), y=expression(log[10]~I[2]))
g2
ggsave(paste0(fig, "lognormal_data_lin.png"), plot=g1, device="png", width=3, height=2.5, dpi=300)
ggsave(paste0(fig, "lognormal_data_log.png"), plot=g2, device="png", width=3, height=2.5, dpi=300)
```


```{r poisson_plates}
set.seed(226)
p <- rpois(20, 7)
d <- data.frame(plate=seq_along(p), cnt = p)

g1 <- ggplot(d, aes(plate, cnt)) +
  theme_classic() +
  #geom_segment(aes(x=plate, xend=plate, y=cnt, yend=0), colour="grey80") +
  geom_point(shape=22, fill=fill.colour) +
  scale_x_continuous(breaks=c(1,5,10,15,20)) +
  scale_y_continuous(expand=c(0,0), limits=c(0, max(p) * 1.05), breaks=2*1:10) +
  labs(x="Plate", y="Count")
g1

x <- 0:16
d <- data.frame(
  x = x,
  y = dpois(x, 7)
)
g2 <- ggplot(d, aes(x, y)) +
  theme_classic() +
  geom_col(fill=fill.colour, colour="black", width=0.8) +
  scale_x_continuous(breaks=0:16) +
  scale_y_continuous(expand=c(0,0), limits=c(0, max(d$y)*1.1)) +
  labs(x = "k", y = "P(X = k)")
g2

ggsave(paste0(fig, "poisson_plates.png"), plot=g1, device="png", width=3.5, height=2.5, dpi=300)
ggsave(paste0(fig, "poisson_dist.png"), plot=g2, device="png", width=3.5, height=2.5, dpi=300)
```


```{r poisson_dist}
mus <- c(0.3, 1, 4, 10)
P <- lapply(mus, function(mu) {
  xp <- 0:20
  p <- data.frame(
    x = xp,
    y = dpois(xp, mu)
  )
  xn <- seq(0, 20, 0.01)
  d <- data.frame(
    x = xn,
    y = dnorm(xn, mu, sqrt(mu))
  )
  
  ggplot() +
    theme_dist +
    geom_segment(data=p, aes(x=x, xend=x, y=y, yend=0), colour="grey80") +
    geom_point(data=p, aes(x, y), shape=21, fill="white") +
    geom_line(data=d, aes(x, y), colour="red") +
    #stat_function(fun=dnorm, args=list(mean=mu, sd=sqrt(mu)), colour="red") +
    scale_x_continuous(breaks=c(0,5,10,15,20)) +
    scale_y_continuous(expand=c(0,0), limits=c(0, max(d$y) * 1.07)) +
    labs(x="k", y="")
})

g <- plot_grid(P[[1]], P[[2]], P[[3]], P[[4]], ncol=1)
g

ggsave(paste0(fig, "poisson_norm_dist.png"), plot=g, device="png", width=3, height=5, dpi=300)

```


```{r horse_kicks}
h <- c(144, 91, 32, 11, 2, 0)
x <- 0:5
mu <- sum(h * x) / sum(h)
d <- data.frame(
  x = x,
  h = h,
  s = sqrt(h),
  p = dpois(x, mu) * sum(h)
)

g <- ggplot(d) +
  geom_col(aes(x, p), fill=fill.colour, width=0.7, colour="grey30") +
  geom_point(aes(x, h), size=2) +
  geom_errorbar(aes(x=x, ymin=h-s, ymax=h+s), width=0.1) +
  scale_x_continuous(breaks=0:5) +
  scale_y_continuous(expand=c(0,0), limits=c(0,160)) +
  labs(x="Deaths per corps-year", y="Count")
g

ggsave(paste0(fig, "horse_kicks.png"), plot=g, device="png", width=4, height=5, dpi=300)

```


```{r binomial}
genBinom <- function(size, prob) {
  x <- 0:size
  d <- data.frame(
    x = x,
    y = dbinom(x, size=size, prob=prob)
  )
}

d <- genBinom(8, 0.5)
g1 <- ggplot(d) +
  geom_col(aes(x, y), fill=fill.colour, width=0.7, colour="grey30") +
  scale_x_continuous(breaks=0:8) +
  scale_y_continuous(expand=c(0,0), limits=c(0,max(d$y)*1.03)) +
  labs(x="Number of successes", y="Probability")
g1

d <- genBinom(100, 0.5)
g2 <- ggplot(d) +
  geom_segment(aes(x=x, xend=x, y=y, yend=0), colour="grey70") +
  geom_point(aes(x=x, y=y), size=2) +
  stat_function(fun=dnorm, args=list(mean=50, sd=sqrt(25)), colour="red") +
  scale_x_continuous(limits=c(35, 65)) +
  scale_y_continuous(expand=c(0,0), limits=c(0,max(d$y)*1.03)) +
  labs(x="Number of successes", y="Probability")
g2

d <- genBinom(100, 0.01)
mu <- 100 * 0.01
d$p <- dpois(d$x, mu)
g3 <- ggplot(d) +
  geom_col(aes(x, p), fill=fill.colour, width=0.7, colour="grey30") +
  geom_segment(aes(x=x, xend=x, y=y, yend=0), colour="grey70") +
  geom_point(aes(x, y), size=2) +
  scale_x_continuous(breaks=0:10, limits=c(-0.5,10)) +
  scale_y_continuous(expand=c(0,0), limits=c(0,0.4)) +
  labs(x="Number of successes", y="Probability")
g3



ggsave(paste0(fig, "binomial_example.png"), plot=g1, device="png", width=4, height=3, dpi=300)
ggsave(paste0(fig, "binomial_example_normal.png"), plot=g2, device="png", width=4, height=3, dpi=300)
ggsave(paste0(fig, "binomial_example_poisson.png"), plot=g3, device="png", width=4, height=3, dpi=300)
```

```{r exercise}
set.seed(10)
dPlot <- function(x) {
  ggplot(data.frame(x=1, y=x), aes(x, y)) +
    theme_classic() +
    theme(
      axis.title.x = element_blank(),
      axis.ticks.x = element_blank(),
      axis.text.x = element_blank()
    ) +
    scale_x_continuous(expand=c(0,0), limits=c(0.5, 1.5)) +
    geom_beeswarm(cex=1, size=0.7, priority="density") +
    labs(x=NULL, y=NULL)
}

a <- 5
b <- 15

m <- (a + b) / 2
v <- (1/12) * (b - a)^2
mu <- log(m / sqrt(1 + v/m^2))
sig <- sqrt(log(1 + v/m^2))

g1 <- dPlot(runif(120, min=a, max=b))
g2 <- dPlot(exp(rnorm(100, mean=mu, sd=sig)))
g3 <- dPlot(rpois(60, lambda=4))
g4 <- dPlot(rnorm(90, mean=100, sd=10))
g5 <- dPlot(rpois(90, lambda=100))

g <- plot_grid(g1, g2, g3, g4, g5, nrow=1)

ggsave(paste0(fig, "exercise.png"), plot=g, device="png", width=7, height=4, dpi=300)

```


```{r r_functions}
theme.d <- theme(
  axis.title = element_blank(),
  axis.ticks = element_blank(),
  axis.text = element_blank(),
  axis.line.y = element_blank()
)

g1 <- plotFun(dnorm, x.grid=seq(-4, 4, 0.01), cut.up = 1.7) +
  theme.d
ggsave(paste0(fig, "dnorm.png"), plot=g1, device="png", width=2, height=1.4, dpi=300)

g2 <- plotFun(dnorm, x.grid=seq(-4, 4, 0.01), cut.lo = -qnorm(0.975), cut.up = qnorm(0.975)) +
  theme.d
ggsave(paste0(fig, "dnorm2.png"), plot=g2, device="png", width=2, height=1.4, dpi=300)

k <- 0:8
d <- data.frame(
  k = k,
  p = dbinom(k, 8, 0.5)
)

g3 <- ggplot(d, aes(x=k, y=p)) +
  theme_dist +
  theme.d +
  #scale_x_discrete(breaks=k, labels=k) +
  scale_y_continuous(expand=c(0,0), limits=c(0, max(d$p) * 1.05)) +
  geom_col(fill=fill.colour, colour="black", width=0.6, size=0.2) +
  labs(x=NULL, y=NULL) +
  geom_col(data=d[7:9, ], fill=fill.colour.dark, colour="black", width=0.6, size=0.2)
g3
ggsave(paste0(fig, "dbinom.png"), plot=g3, device="png", width=2, height=1.4, dpi=300)

```