---
title: "Probability distributions"
output:
  html_document:
    css: tabbed_notebook.css
    fig_width: 3
    fig_height: 3
params: 
  output_dir: "../output"
---

```{r setup, echo=FALSE}
root <- "02_errors_and_statistical_estimators"
source("../R/setup.R")
library(beeswarm)
library(ggbeeswarm)
knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  echo = FALSE,
  cache = TRUE,
  cache.path = paste0("../cache/", root),
  fig.path = paste0("../cache/", root)
)
fig <- paste0("../fig/", root, "/")
if(!dir.exists(fig)) dir.create(fig)
```

```{css echo=FALSE}
pre code, pre, code {
  white-space: pre !important;
  overflow-x: scroll !important;
  word-break: keep-all !important;
  word-wrap: initial !important;
}
```


```{r mini_normal}
d <- rnorm(10000)

df <- data.frame(d = d)
brks <- seq(-4, 4, 0.1)

dst <- ggplot(df, aes(x=d, y=..density..)) +
  theme_dist +
  theme(
    axis.line.y = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank()
  ) +
  scale_x_continuous(expand=c(0,0)) +
  scale_y_continuous(expand=c(0,0)) +
  geom_histogram(breaks=brks, fill=fill.colour) +
  labs(x="", y="")
g <- dst + geom_outline(d, brks, size=0.3)
g

ggsave(paste0(fig, "mini_normal.png"), plot=g, device="png", width=2, height=2, dpi=300)
```


```{r normal_gene}
dat <- read.table("../data/WT_lev.tsv", sep="\t", header=FALSE)
x <- as.integer(dat[dat$V1 == "ybr019c", 2:ncol(dat)])
x <- x[c(-21,-22,-25,-28,-31,-34,-36)]  # clean replicates
df <- data.frame(x = x)
bs <- beeswarm(x, do.plot = FALSE, cex=2)
M <- mean(x)
S <- sd(x)
xx <- seq(30, 150, 1)
gs <- data.frame(x=xx, y=dnorm(xx, mean=M, sd=S))

lims <- c(30, 120)

# data plot
g1 <- ggplot(bs, aes(x=y, y=x)) +
  theme_dist +
  theme(axis.text = element_text(size=12)) +
  theme(
    axis.line.y.right = element_line(),
    axis.ticks.y = element_blank(),
    axis.text.y = element_blank(),
    plot.margin = margin(t=-1)
  ) +
  geom_point(size=1.5) +
  labs(x = "Count", y="") +
  scale_y_continuous(expand=c(0,0), limits=c(0.5,1.5)) +
  scale_x_continuous(limits=lims)

# main plot
g2 <- ggplot(df, aes(x=x, y=..density..)) +
  theme_dist +
  theme(
    axis.text = element_text(size=12),
    axis.title.x = element_blank(),
    axis.text.x = element_blank(),
    axis.ticks.x = element_blank(),
    plot.margin = margin(l=3, r=2, b=0, t=1)
  ) +
  geom_histogram(bins=16, fill=fill.colour) +
  geom_line(data=gs, aes(x,y), colour="red") +
  scale_y_continuous(expand=c(0,0), limits=c(0,0.038), breaks=1:5/100) +
  labs(x=NULL) +
  scale_x_continuous(limits=lims)

g <- plot_grid(g2, g1, ncol=1, align = "v", rel_heights = c(3, 1))
g

ggsave(paste0(fig, "normal_gene.png"), plot=g, device="png", width=4, height=4.5, dpi=300)
```


```{r counting_error}
set.seed(2002)

d <- rpois(10000, 11)
M <- mean(d)
S <- sd(d)
dm <- data.frame(
  M = M,
  S = S
)

df <- data.frame(
  i = seq_along(d),
  cnt = d,
  err = sqrt(d)
)
tb <- table(d)
dist <- data.frame(
  x = 0:50,
  y = 0
)
dist[as.integer(names(tb))+1, "y"] <- as.numeric(tb)
dist$y <- dist$y / sum(dist$y)

lims <- c(0, 23)

# top panel
g1 <- ggplot(df[1:16, ]) +
  theme_classic() +
  coord_flip() +
  geom_errorbar(aes(x=i, ymin=cnt-err, ymax=cnt+err), width=0.2) +
  geom_point(aes(i, cnt)) +
  labs(y=NULL, x="Plate no.") +
  scale_x_continuous(breaks=c(1:16)) +
  scale_y_continuous(limits=lims) +
  geom_hline(yintercept = 11, colour="darkolivegreen", linetype="dotted")
  #theme(
  #  plot.margin = margin(l=3, r=2, b=1, t=1)
  #) 

# bottom panel
mx <- max(dist$y) * 1.3
yerr <- mx - 0.01
g2 <- ggplot(dist) +
  theme_dist +
  geom_segment(aes(x=x, xend=x, y=y, yend=0), colour="grey70") +
  geom_point(aes(x, y), size=2) +
  labs(x="Colony count", y="Normalized frequency") +
  scale_x_continuous(limits=lims) +
  scale_y_continuous(expand=c(0,0), limits=c(0, mx), breaks=c(0, 0.05, 0.1)) +
  geom_errorbarh(data=dm, aes(x=M, xmin=M-S, xmax=M+S, y=yerr), height=2, colour="darkolivegreen") +
  geom_point(data=dm, aes(x=M, y=yerr), colour="darkolivegreen")
  
g <- plot_grid(g1, g2, ncol=1, align = "v", rel_heights = c(2.5, 1))
g

ggsave(paste0(fig, "poisson_plates.png"), plot=g, device="png", width=4, height=4.5, dpi=300)
```


```{r murder}
murderPlot <- function(d) {
  ggplot(d) +
  theme_classic() +
  geom_errorbar(aes(x=City, ymin=Rate-Error, ymax=Rate+Error), width=0.2) +
  geom_point(aes(x=City, y=Rate), size=2) +
  labs(x=NULL, y="Murder rate per 100,000") +
  scale_y_continuous(expand=c(0,0), limits=c(0, 6))
}

cities <- c("Dundee", "Glasgow", "Aberdeen", "Edinburgh")
dat <- data.frame(
  City = cities,
  Murders = c(6, 19, 2, 2),
  Rate = c(4.1, 3.2, 0.88, 0.41)
)
dat$Error <- dat$Rate * sqrt(dat$Murder) / dat$Murders
dat$City <- factor(dat$City, levels=cities)

g1 <- murderPlot(dat[1:2, ])
g2 <- murderPlot(dat)
g1
g2

ggsave(paste0(fig, "murder_1.png"), plot=g1, device="png", width=3, height=3, dpi=300)
ggsave(paste0(fig, "murder_2.png"), plot=g2, device="png", width=3, height=3, dpi=300)
```


```{r population_and_sample}
set.seed(14)
mu <- 20
sigma <- 5
n <- 30

x <- rnorm(n, mu, sigma)
M <- mean(x)
S <- sd(x)

df <- data.frame(x=1, y=x)

#bs <- beeswarm(y ~ x, data=df, do.plot=TRUE, cex=1)

g <- ggplot(df) +
  theme_classic() +
  theme(
    axis.ticks.x = element_blank(),
    axis.text.x = element_blank()
  ) +
  geom_beeswarm(aes(x, y), size=1.7, shape=21, cex=3, colour="darkolivegreen", fill="goldenrod1") +
  geom_errorbar(aes(x=0.85, ymin=M-S, ymax=M+S), width=0.1, colour="darkolivegreen") +
  geom_point(aes(x=0.85, y=M), colour="darkolivegreen") +
  geom_errorbar(aes(x=0, ymin=mu-sigma, ymax=mu+sigma), width=0.1) +
  geom_point(aes(x=0, y=mu)) +
  labs(x=NULL, y="Body mass (g)") +
  scale_x_continuous(limits=c(-0.4, 1.4))

g
ggsave(paste0(fig, "population_sample.png"), plot=g, device="png", width=3, height=3.5, dpi=300)

```


```{r standard_deviation}
set.seed(1002)

x <- rnorm(12, 20, 5)
M <- mean(x)
S <- sd(x)

df <- data.frame(x=seq_along(x), y=x)

g <- ggplot(df, aes(x=x, y=y)) +
  theme_classic() +
  geom_segment(aes(xend=x, yend=M), colour="grey70") +
  geom_point(aes(x, y), size=1.7, shape=21, colour="black", fill="darkgoldenrod1") +
  geom_hline(yintercept = M, linetype="dotted", colour="grey50") +
  labs(x="Data point", y="Body mass (g)") +
  scale_x_continuous(breaks=1:12)
  
g
ggsave(paste0(fig, "standard_deviation.png"), plot=g, device="png", width=3.5, height=3, dpi=300)
```


```{r sampling_distribution_mean_generate}
set.seed(1492)

pop <- rnorm(100000, 20, 5)
sam5 <- t(replicate(100000, sample(pop, 5)))
sam5.mean <- rowMeans(sam5)
sam30 <- t(replicate(100000, sample(pop, 30)))
sam30.mean <- rowMeans(sam30)
```


```{r sampling_distribution}
g1 <- plotOneDist(pop, "Mouse weight (g)", "Population", c(0, 40), with.outline = TRUE)
g2 <- plotOneDist(sam5.mean, "Sample mean weight (g)", "Sample means", c(0, 40), with.outline = TRUE)
g <- plot_grid(g1, g2, ncol=2)
g 
 
ggsave(paste0(fig, "population_sample_dist.png"), plot=g, device="png", width=8, height=4, dpi=300)
```


```{r sampling_distribution_mean_function}
plotSamplingMean <- function(sam, lims=c(0, 40), nsub=8, seed=123, cex=2, size=1, bins=100, with.errors=FALSE) {
  set.seed(seed)

  sam.mean <- rowMeans(sam)
  MM <- mean(sam.mean)
  SS <- sd(sam.mean)
  
  n <- nrow(sam)
  subsam <- sam[sample(1:n, nsub), ]
  m <- melt(subsam)
  mm <- data.frame(
    i = 1:nsub,
    M = apply(subsam, 1, mean),
    S = apply(subsam, 1, sd)
  )
  mm$SE <- mm$S / sqrt(ncol(sam))
  print(round(subsam, 2))
  print(mm)
  
  lmar <- 5
  rmar <- 6
  
  # top panel
  shift <- 0.2
  err.col <- ifelse(with.errors, "grey50", "black")
  g1 <- ggplot(m) +
    theme_classic() +
    coord_flip() +
    geom_beeswarm(aes(x=Var1, y=value), cex=cex, size=size, shape=21, colour="grey50", fill="darkgoldenrod1") +
    labs(y="Mouse weight (g)", x="Sample no.") +
    scale_x_continuous(breaks=c(1:nsub)) +
    scale_y_continuous(limits=lims, expand=c(0,0)) +
    geom_hline(yintercept = MM, colour="darkolivegreen", linetype="dotted") +
    theme(
      plot.margin = margin(b=-2, l=lmar, r=rmar)
    )
  if(with.errors) {
    g1 <- g1 +
      geom_errorbar(data=mm, aes(x=i+shift, ymin=M-S, ymax=M+S), width=0.2, colour=err.col) +
      geom_errorbar(data=mm, aes(x=i+shift, ymin=M-SE, ymax=M+SE), width=0.2, colour="black") +
      geom_point(data=mm, aes(i+shift, M), shape=15, size=1.5)
  } else {
    g1 <- g1 +
      geom_segment(data=mm, aes(x=i-shift, xend=i+shift, y=M, yend=M))
  }
  

  # bottom panel
  brks <- seq(lims[1], lims[2], length.out = bins)
  g2 <- ggplot(data.frame(d=sam.mean), aes(x=d, y=..density..)) +
    theme_classic() +
    geom_histogram(breaks=brks, fill=fill.colour.mid) +
    labs(x="Mean sample weight (g)", y="Density", title=NULL) +
    scale_x_continuous(expand=c(0,0)) +
    scale_y_continuous(expand=c(0,0)) +
    geom_outline(sam.mean, brks, colour="grey50") +
    theme(
      plot.margin = margin(t=-2, l=lmar, r=rmar)
    ) 
  
  # mid plot
  g3 <- ggplot(data.frame(M=MM, S=SS)) +
    theme_nothing() +
    theme(
      plot.margin = margin(t=-1, b=-5, l=lmar, r=rmar)
    ) +
    #geom_errorbarh(aes(xmin=M-S, xmax=M+S, y=0), width=0.1) +
    geom_segment(aes(x=M-S, xend=M+S, y=0, yend=0), colour="darkolivegreen") +
    geom_point(aes(x=M, y=0), colour="darkolivegreen") +
    scale_y_continuous(expand=c(0,0), limits=c(-0.5, 0.5)) +
    scale_x_continuous(expand=c(0,0), limits=lims)
    
  
  g <- plot_grid(g1, g3, g2, ncol=1, align = "v", rel_heights = c(3, 0.3, 1)) 
  g
}
```


```{r sampling_mean}
g1 <- plotSamplingMean(sam5, seed=1007, bins=150)
g1
 
g2 <- plotSamplingMean(sam30, seed=13, cex=1, size=0.5, bins=300)
g2
 
ggsave(paste0(fig, "sampling_mean5.png"), plot=g1, device="png", width=4, height=4.5, dpi=300)
ggsave(paste0(fig, "sampling_mean30.png"), plot=g2, device="png", width=4, height=4.5, dpi=300)
```

```{r sampling_mean_se}
g1 <- plotSamplingMean(sam5, seed=1007, bins=150, cex=1, size=0.5, with.errors=TRUE)
g2 <- plotSamplingMean(sam30, seed=13, cex=1, size=0.5, bins=300, with.errors=TRUE)
 
g <- plot_grid(g1, g2, ncol=2) 

ggsave(paste0(fig, "sampling_mean_se.png"), plot=g, device="png", width=7, height=4.5, dpi=300)
```

```{r correlation, fig.width=9}
set.seed(233)
x <- runif(30)

d1 <- data.frame(x=x, y=x + 0.1 * rnorm(30))
d2 <- data.frame(x=x, y=runif(30))
d3 <- data.frame(x=x, y=1-x + 0.1 * rnorm(30))

plotR <- function(d) {
  r <- round(cor(d$x, d$y),2)
  ggplot(d, aes(x, y)) +
    theme_classic() +
    geom_point() +
    scale_x_continuous(limits=c(0, 1)) +
    scale_y_continuous(limits=c(0, 1)) +
    annotate("text", x=0.17, y=0.99, label=paste0("r = ", r))
}

g1 <- plotR(d1)
g2 <- plotR(d2)
g3 <- plotR(d3)

g <- plot_grid(g1, g2, g3, ncol=3)
g

ggsave(paste0(fig, "correlation.png"), plot=g, device="png", width=7, height=2.5, dpi=300)

```


