---
title: "Confidence intervals 1"
output:
  html_document:
    css: tabbed_notebook.css
    fig_width: 3
    fig_height: 3
params: 
  output_dir: "../output"
---

```{r setup, echo=FALSE}
root <- "03_confidence_intervals"
source("../R/setup.R")
library(beeswarm)
library(ggbeeswarm)
knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  echo = FALSE,
  cache = TRUE,
  cache.path = paste0("../cache/", root),
  fig.path = paste0("../cache/", root)
)
fig <- paste0("../fig/", root, "/")
if(!dir.exists(fig)) dir.create(fig)
```

```{css echo=FALSE}
pre code, pre, code {
  white-space: pre !important;
  overflow-x: scroll !important;
  word-break: keep-all !important;
  word-wrap: initial !important;
}
```



```{r 95_ci_generate}
set.seed(1001)
n <- 30
nsim <- 100
M <- 20
S <- 5
Z <- qnorm(0.975)

while(TRUE) {
  P <- lapply(1:nsim, function(i) {
    x <- rnorm(n, M, S)
    ci <- Z * sd(x) / sqrt(n)
    m <- mean(x)
    data.frame(i = i, m = m, lo = m - ci, up = m + ci, nc = abs(m - M) / ci)
  })
  d <- do.call(rbind, P)
  if(length(which(d$nc > 1)) == 5) break()
}
```

```{r 95_ci_plot, fig.width=7}
g <- ggplot(d) + 
  theme_classic() +
  geom_errorbar(aes(x=i, ymin=lo, ymax=up), width=0.3, colour="grey70") +
  geom_errorbar(data=subset(d, nc>1), aes(x=i, ymin=lo, ymax=up), width=0.6, colour="black") +
  geom_point(aes(x=i, y=m), size=0.8) +
  labs(x="Experiment", y="Body mass (g)") +
  geom_hline(yintercept = M, colour="red", linetype="dotted")

g
ggsave(paste0(fig, "95_ci.png"), plot=g, device="png", width=6, height=2.5, dpi=300)
```

```{r sampling_distributions_generate}
set.seed(987)
n <- 5
nsim <- 100000
mu <- 20
sigma <- 5
P <- mclapply(1:nsim, function(i) {
  x <- rnorm(n, mu, sigma)
  M <- mean(x)
  S <- sd(x)
  SE <- S / sqrt(n)
  data.frame(
    Mean = M,
    Median = median(x),
    `Standard deviation` = S,
    IQR = IQR(x),
    `Median deviation` = mad(x),
    t = (M - mu) / SE,
    check.names = FALSE
  )
})
sam.dist <- do.call(rbind, P)
```



```{r sampling_distributions_plot}
lms <- list(
  Mean = c(10, 30),
  Median = c(10, 30),
  `Standard deviation` = c(0, 12),
  IQR = c(0, 17),
  t = c(-6, 6)
)

P <- lapply(colnames(sam.dist)[1:4], function(nm) {
  plotOneDist(sam.dist[, nm], nm, "", limits=lms[[nm]], with.outline = TRUE) +
    labs(y=NULL) +
    theme(
      axis.text.y = element_blank(),
      axis.line.y = element_blank(),
      axis.ticks.y = element_blank()
    )
})
g <- plot_grid(P[[1]], P[[2]], P[[3]], P[[4]], ncol=2)
g
 
ggsave(paste0(fig, "sampling_distributions.png"), plot=g, device="png", width=4, height=4, dpi=300)
```

```{r sampling_distribution_mean}
plotDistCI <- function(x, brks, p = 0.05) {
  q.up <- quantile(x, 1 - 0.5*p)
  q.lo <- quantile(x, 0.5*p)
  plotDistributionCut(x, cut=q.up, locut=q.lo, side = "two", brks=brks, fill=fill.colour, xlab="")
}


g1 <- plotDistCI(sam.dist$Mean, brks=seq(10, 30, 0.1))
g1
ggsave(paste0(fig, "sampling_distributions_mean_cut.png"), plot=g1, device="png", width=3.5, height=3, dpi=300)

g2 <- plotDistCI(sam.dist$t, brks=seq(-6, 6, 0.05))
g2
ggsave(paste0(fig, "sampling_distributions_t_cut.png"), plot=g2, device="png", width=3.5, height=3, dpi=300)
```


```{r t_cut_function}
tCut <- function(t.obs, dof) {
  x <- seq(-5, 5, 0.01)
  y <- dt(x, dof)
  dft <- data.frame(
    x = c(-5, x, 5),
    y = c(0, y, 0)
  )
  

  x <- seq(t.obs, 5, 0.01)
  df <- data.frame(
    x = c(t.obs, x, max(x), t.obs),
    y = c(0, dt(x, dof), 0, 0)
  )
  df1 <- df
  df1$x <- -df1$x

  g1 <- ggplot(df, aes(x=x, y=..density..)) +
    theme_dist +
    #geom_line(data=dft, aes(x, y), colour="blue") +
    geom_polygon(data=dft, aes(x, y), colour="black", fill=fill.colour) +
    labs(x="t", y="Density") +
    scale_x_continuous(limits=c(-5, 5), expand=c(0,0)) +
    scale_y_continuous(limits=c(0, max(dft$y)*1.03), expand=c(0,0))
  g2 <- g1 + geom_polygon(data=df, aes(x, y), colour="black", fill=fill.colour.dark)
  g3 <- g2 + geom_polygon(data=df1, aes(x, y), colour="black", fill=fill.colour.dark)
  list(t=g1, t.one=g2, t.two=g3)
}
```

```{r t_dist_cut}
tcut <- qt(0.975, 4)
tplot <- tCut(tcut, 4)
tplot$t.two

ggsave(paste0(fig, "t_distribution_cut.png"), plot=tplot$t.two, device="png", width=3.5, height=3, dpi=300)
```

```{r standard_error}
g <- plotDistributionCut(sam.dist$Mean, cut=NULL, brks=seq(10,30,0.1), fill=fill.colour, xlab="")
g

ggsave(paste0(fig, "sampling_distribution.png"), plot=g, device="png", width=3.5, height=3, dpi=300)
```


```{r r_functions}
theme.d <- theme(
  axis.title = element_blank(),
  axis.ticks = element_blank(),
  axis.text = element_blank(),
  axis.line.y = element_blank()
)

q <- qt(0.975, 4)
g1 <- plotFun(dt, df=4, x.grid=seq(-5, 5, 0.01), cut.up = q) +
  theme.d
ggsave(paste0(fig, "dt.png"), plot=g1, device="png", width=2, height=1.4, dpi=300)

g2 <- plotFun(dt, df=4, x.grid=seq(-5, 5, 0.01), cut.up = q, cut.lo = -q) +
  theme.d
ggsave(paste0(fig, "dt2.png"), plot=g2, device="png", width=2, height=1.4, dpi=300)

d <- c(16.8, 21.8, 29.2, 23.3, 26.3)
n <- length(d)
M <- mean(d)
SE <- sd(d) / sqrt(n)
# critical t
tc <- qt(0.975, df = n - 1)
# lower confidence limit
M - tc * SE
# upper confidence limit
M + tc * SE

```

```{r ci_vs_se}
errPlot <- function(n, p.size=1, cex=1) {
  x <- rnorm(n)
  M <- mean(x)
  S <- sd(x)
  SE <- S / sqrt(n)
  CI <- SE * qt(0.975, n - 1)
  errv <- c(S, SE, CI)

  d <- data.frame(x=1, y=x)
  d.err <- data.frame(
    x = 2:4,
    y = M,
    ymin = M - errv,
    ymax= M + errv
  )
  g <- ggplot() +
    theme_classic() +
    theme(
      axis.line.y = element_line(arrow=arrow(type="closed", angle=20, length=unit(3, "mm"))),
      axis.ticks = element_blank(),
      axis.text.y = element_blank(),
      plot.margin = margin(l=6, b=5)
    ) +
    geom_beeswarm(data=d, aes(x, y), cex=cex, size=p.size, shape=21, fill=fill.colour, colour="grey40") +
    geom_errorbar(data=d.err, aes(x=x, ymin=ymin, ymax=ymax), width=0.2) +
    geom_point(data=d.err, aes(x, y), size=2, shape=21, fill="white", colour="black") +
    scale_x_continuous(limits=c(0.5, 4.5), breaks=1:4, labels=c("Sample", "SD", "SE", "95%CI"))  +
    labs(x=NULL, y="Measured value")
  g
}

set.seed(10)
g0 <- errPlot(2)
g0
ggsave(paste0(fig, "sd_se_ci_2.png"), plot=g0, device="png", width=4, height=3, dpi=300)


set.seed(1112)
g1 <- errPlot(8)
g1
ggsave(paste0(fig, "sd_se_ci_8.png"), plot=g1, device="png", width=4, height=3, dpi=300)

g2 <- errPlot(100, cex=1.5) + labs(y="") + theme(plot.margin = margin(l=20))
g2
g <- plot_grid(g1, g2, ncol=2, align="h", rel_widths = c(1, 1.1))

ggsave(paste0(fig, "sd_se_ci_comparison.png"), plot=g, device="png", width=5, height=3, dpi=300)
```

```{r ci_and_se}
cPlot <- function(x, y, ylab, yintercept, ylim=NULL, ...) {
  g <- ggplot(data=data.frame(x=x, y=y)) +
    theme_classic() +
    theme(plot.margin = margin(l=5, t=15, r=5)) +
    geom_hline(yintercept = yintercept, colour="red", linetype="dotted") +
    geom_line(aes(x, y), colour="grey70") +
    geom_point(aes(x, y)) +
    scale_x_continuous(expand=c(0,0), limits=c(0.01, max(x)+1), breaks=c(2, seq(5,max(x), 5))) +
    labs(x="Sample size", y=ylab)
  if(!is.null(ylim)) {
    g <- g + scale_y_continuous(expand=c(0,0), limits=ylim, ...)
  }
  g
}

x <- 2:30
g1 <- cPlot(x=x, y=qt(0.975, x-1), expression(t[c]), qnorm(0.975), ylim=c(0,13), breaks=seq(2,14,2))
g2 <- cPlot(x=x, y=1 - 2*pt(-1, x-1), "Confidence of SE", 1 - 2*pnorm(-1))
g <- plot_grid(g1, g2, ncol=1, align="v")
g

ggsave(paste0(fig, "se_and_ci.png"), plot=g, device="png", width=3.2, height=4, dpi=300)

```

```{r example_ci}
d <- c(16.8, 21.8, 29.2, 23.3, 19.5, 18.2, 26.3)
t.test(d)
```

```{r exercise_ci}
d <- data.frame(
  Day = c(rep(1, 3), rep(2, 5)),
  Value = c(0.89, 0.92, 0.90, 0.55, 0.76, 0.61, 0.83, 0.75)
)
sm <- d %>%
  group_by(Day) %>%
  summarise(m = mean(Value), ci = qt(0.975, n() - 1) * sd(Value) / sqrt(n())) %>%
  mutate(lo = m - ci, up = m + ci)

g1 <- ggplot() +
  theme_classic() +
  geom_point(data=d, aes(Day, Value), shape=21, size=2, fill=fill.colour) +
  scale_x_continuous(limits=c(0.5,2.5), breaks=c(1,2)) +
  ylim(0.5, 1)
g1
g2 <- g1 +
  geom_errorbar(data=sm, aes(x=Day-0.1, ymin=lo, ymax=up), width=0.1) +
  geom_point(data=sm, aes(Day-0.1, m), size=2)
g2

ggsave(paste0(fig, "excercise_1.png"), plot=g1, device="png", width=3, height=3.5, dpi=300)
ggsave(paste0(fig, "excercise_1_ci.png"), plot=g2, device="png", width=3, height=3.5, dpi=300)
```


```{r binomial_median_ci}
n <- 8
x <- 0:n
d <- data.frame(
  x = x,
  y = dbinom(x, size=n, prob=0.5)
)

ci <- 1 - 2 * pbinom(0:floor(n/2), size=n, prob=0.5)
ci

g <- ggplot(d) +
  theme_classic() +
  geom_segment(aes(x=x, xend=x, y=0, yend=y), colour="grey70") +
  geom_point(aes(x, y)) +
  geom_text(aes(x=x, y=y, label=round(y,3)), nudge_y = 0.04, size=3) +
  labs(x="", y="Probability") +
  scale_x_continuous(breaks=0:n, labels=d$x) +
  scale_y_continuous(expand=c(0,0), limits=c(0, max(d$y) * 1.2))
g

ggsave(paste0(fig, "binomial_median_ci.png"), plot=g, device="png", width=4.5, height=1.8, dpi=300)
```


```{r ci_median}
x <- c(14.9, 15.6, 18.6, 19.1, 20.1, 20.6, 21.4, 22.0, 24.8)

```