---
title: "Data presentation"
output:
  html_document:
    css: tabbed_notebook.css
    fig_width: 3
    fig_height: 3
params: 
  output_dir: "../output"
---

```{r setup, echo=FALSE}
root <- "05_data_presentation"
source("../R/setup.R")
library(lemon)
library(ggbeeswarm)
library(scales)
knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  echo = FALSE,
  cache = TRUE,
  cache.path = paste0("../cache/", root),
  fig.path = paste0("../cache/", root)
)
fig <- paste0("../fig/", root, "/")
if(!dir.exists(fig)) dir.create(fig)
```

```{css echo=FALSE}
pre code, pre, code {
  white-space: pre !important;
  overflow-x: scroll !important;
  word-break: keep-all !important;
  word-wrap: initial !important;
}
```


```{r good_plot}
set.seed(344)
gpModel <- function(x, A=1, tau=16) {
  y <- A * exp(-x / tau)
}
x <- c(0.5, 1, 2, 4, 8, 12, 16, 24, 48)
m <- gpModel(x)
y <- sapply(m, function(M) {
  s <- rnorm(12, M, 0.15)
  c(mean=mean(s), se=sd(s) / sqrt(length(s)))
}) %>% t %>% as.data.frame

d <- data.frame(
  x = x,
  y
)
d$w <- 1 / d$se^2
d$w <- d$w / sum(d$w)

fit <- nls(mean ~ A * exp(-x / tau), data=d, weights=d$w, start=c(A=1, tau=10))
cf <- summary(fit)$coefficients[,1:2]
cf
cf[, 2] * qnorm(0.975)

xx <- seq(0, 50, 0.1)
dm <- data.frame(
  x = xx,
  y = cf[1, 1] * exp(-xx / cf[2, 1])
)


g <- ggplot(d) +
  theme_classic() +
  geom_line(data=dm, aes(x, y), colour="darkolivegreen4") +
  geom_errorbar(aes(x=x, ymin=mean-se, ymax=mean+se), width=0.2) +
  geom_point(aes(x=x, y=mean)) +
  labs(x= "Time (h)", y="Relative abundance") +
  scale_y_continuous(expand=c(0,0), limits=c(0, max(d$mean + d$se) * 1.03))
g

ggsave(paste0(fig, "good_plot.png"), plot=g, device="png", width=4.5, height=3, dpi=300) 
```

```{r show_your_data, fig.width=7, fig.height=3}
set.seed(1001)
n1 <- 30
n2 <- 35
d <- data.frame(
  type = c(rep("WT", n1), rep("KO", n2)),
  value = c(rnorm(n1, 20, 5), rnorm(n2, 25, 7))
)
d$type <- relevel(d$type, ref="WT")

dm <- d %>% group_by(type) %>% summarise(M = mean(value), SE = sd(value) / sqrt(n()))

g0 <- ggplot() +
  theme_classic() +
  theme(legend.position = "none") +
  scale_fill_manual(values=cbPalette) +
  labs(x=NULL, y=NULL)
  
g1 <- g0 +
  geom_errorbar(data=dm, aes(x=type, ymin=M-SE, ymax=M+SE), width=0.3, colour="black") +
  geom_col(data=dm, aes(x=type, y=M)) +
  scale_y_continuous(expand=c(0,0), limits=c(0, max(dm$M + dm$SE) * 1.03 )) +
  labs(y="Mass (g)")

g2 <- g0 +
  geom_boxplot(data=d, aes(x=type, y=value, fill=type))

g3 <- g0 +
  geom_jitter(data=d, aes(x=type, y=value, fill=type), shape=21, width=0.2, height=0)


g4 <- g0 +
  geom_beeswarm(data=d, aes(x=type, y=value, fill=type), shape=21, cex=4.5)
 
g <- plot_grid(g1, g2, g3, g4, ncol=4, align = "v")
g

ggsave(paste0(fig, "show_your_data.png"), plot=g, device="png", width=7, height=3, dpi=300) 
```


```{r lines_and_symbols, fig.width=9}
emptyBox <- function(ann="") {
  ggplot() +
    theme_classic() +
    theme(
      axis.text = element_blank(),
      axis.ticks = element_blank(),
      axis.line = element_blank(),
      plot.background = element_rect(fill=NA, colour="black"),
      plot.margin = margin(t=1, b=0, l=5, r=5)
    ) +
    labs(x=NULL, y=NULL, title=NULL) +
    scale_x_continuous(expand=c(0.2,0)) +
    scale_y_continuous(expand=c(0.2,0)) +
    annotate("text", Inf, -Inf, label=ann, hjust=1, vjust=-0.4)
}

# symbol shape
x <- 1:5
d1 <- data.frame(x=x, y=x^2)
gt <- emptyBox("bad") + geom_point(data=d1, aes(x, y), shape=8, size=2)
gb <- emptyBox("good") + geom_point(data=d1, aes(x, y), shape=16, size=1.2)
g1 <- plot_grid(gt, gb, ncol=1)

# two groups symbol
x <- 1:20
d2 <- data.frame(
  x = x,
  y1 = x^0.5,
  y2 = 0.3 + x^0.51
)
gt <- emptyBox("bad") +
  geom_point(data=d2, aes(x, y1), shape=21, fill="black") +
  geom_point(data=d2, aes(x, y2), shape=21, fill="black")
gb <- emptyBox("good") + 
  geom_point(data=d2, aes(x, y1), shape=21, fill="white") +
  geom_point(data=d2, aes(x, y2), shape=21, fill="black")
g2 <- plot_grid(gt, gb, ncol=1)

# large symbols
x <- 1:200
y <- x + rnorm(length(x), 0, 10)
d3 <- data.frame(x=x, y=y)
gt <- emptyBox("bad") + geom_point(data=d3, aes(x, y), shape=0, size=2)
gb <- emptyBox("good") + geom_point(data=d3, aes(x, y), shape=16, size=0.4)
g3 <- plot_grid(gt, gb, ncol=1)

# symbols vs lines
x <- 1:100
y1 <- log(x) + rnorm(length(x), 0, 0.05)
y2 <- 1.03 * log(x) * cos(0.04*x/(2*pi)) + rnorm(length(x), 0, 0.05)
d4 <- data.frame(x=x, y1=y1, y2=y2)
gt <- emptyBox("not great") + 
  geom_point(data=d4, aes(x, y1), shape=16, size=0.8, colour="red") +
  geom_point(data=d4, aes(x, y2), shape=16, size=0.8, colour="green")
gb <- emptyBox("better") + 
  geom_line(data=d4, aes(x, y1), colour=cbPalette[1], alpha=0.8) +
  geom_line(data=d4, aes(x, y2), colour=cbPalette[2], alpha=0.8)
g4 <- plot_grid(gt, gb, ncol=1)

# spline
x <- 1:5
y1 <- c(1, 5, 10, 9, 6)
y2 <- c(2, 4, 7, 5, 3.5)
d5 <- data.frame(x=x, y1=y1, y2=y2)

s1 <- spline(x, y1, n=100)
s2 <- spline(x, y2, n=100)
d5s <- data.frame(x=s1$x, y1=s1$y, y2=s2$y)

gt <- emptyBox("bad") +
  geom_line(data=d5s, aes(x, y1), colour="grey40") +
  geom_line(data=d5s, aes(x, y2), colour="black") +
  geom_point(data=d5, aes(x, y1), shape=22, colour="grey40", fill="white") +
  geom_point(data=d5, aes(x, y2), shape=22, colour="black", fill="black")
gb <- emptyBox("good") + 
  geom_pointpath(data=d5, aes(x, y1), shape=22, colour="grey40", fill="white", linecolour="grey40") +
  geom_pointpath(data=d5, aes(x, y2), shape=22, colour="black", fill="black")
g5 <- plot_grid(gt, gb, ncol=1)


g <- plot_grid(g1, g2, g3, g4, g5, nrow=1)
g
ggsave(paste0(fig, "lines_and_symbols.png"), plot=g, device="png", width=7, height=3, dpi=300) 
```


```{r log_lin_1, fig.width=6, fig.height=6}
set.seed(43)

d0 <- read.table("../data/WT_lev.tsv", header=FALSE, sep="\t")
d0 <- d0[, c(2, 3)]
names(d0) <- c("x", "y")
d0 <- d0[d0$x > 0 & d0$y > 0,]
d <- d0[sample(1:nrow(d0), 1000), ]

mx <- max(d) * 1.03
mx <- 25000
p.size <- 0.5

g1 <- ggplot(d) +
  theme_classic() +
  theme(plot.margin = margin(r=15)) +
  geom_point(aes(x, y), size=p.size) +
  scale_x_continuous(expand=c(0,0), limits=c(0, mx)) +
  scale_y_continuous(expand=c(0,0), limits=c(0, mx)) +
  labs(x="Sample 1", y="Sample 2")
g2 <- ggplot(d) +
  theme(plot.margin = margin(r=15)) +
  theme_classic() +
  geom_point(aes(log10(x), log10(y)), size=p.size) +
  labs(x=expression(log[10]~Sample~1), y=expression(log[10]~Sample~2))

g3 <- plotOneDist(d0$x, "Expression", "", c(0, 25000), with.outline = TRUE) + theme_classic() +   theme(plot.margin = margin(r=15)) 

g4 <- plotOneDist(log10(d0$x), expression(log[10]~expression), "", c(-0.1, 5.5), with.outline = TRUE) + theme_classic()

g <- plot_grid(g1, g3, g2, g4, ncol=2, align="hv")
g

ggsave(paste0(fig, "linear_vs_logarithmic_1.png"), plot=g, device="png", width=6, height=5, dpi=300)
```

```{r log_lin_2, fig.width=6, fig.height=6}
d <- data.frame(
  x = 1:6 / 6,
  y1 = c(1.3, 1.5, 2.5, 3.0, 3.6, 4.1),
  s1 = 0.2
)
d$y2 <- 10^d$y1
d$s2 <- log(10) * d$y2 * d$s1

g0 <- ggplot(d) +
  theme_classic() +
  scale_x_continuous(expand=c(0,0), limits=c(0,1.1), breaks=seq(0,1,0.2)) +
  labs(x="Time (d)")
  
g1 <- g0 +
  geom_errorbar(aes(x=x, ymin=y2-s2, ymax=y2+s2), width=0.03) +
  geom_point(aes(x=x, y=y2)) +
  scale_y_continuous(expand=c(0,0), limits=c(0,20000)) +
  labs(y="Abundance")

g2 <- g0 +
  geom_errorbar(aes(x=x, ymin=y1-s1, ymax=y1+s1), width=0.03) +
  geom_point(aes(x=x, y=y1)) +
  scale_y_continuous() +
  labs(y=expression(log[10]~abundance))

set.seed(77)
n1 <- 50
n2 <- 100
d <- data.frame(
  type = c(rep("WT", n1), rep("KO", n2)),
  log.value = c(rnorm(n1, 2.1, 0.3), rnorm(n2, 1.1, 0.2))
)
d$type <- relevel(d$type, ref="WT")
d$value <- as.integer(10^d$log.value)
d$log.value <- log10(d$value)

g0 <- ggplot(d) +
  theme_classic() +
  theme(legend.position = "none") +
  labs(x=NULL, y="Cell count") +
  theme(
    axis.title.y = element_text(margin = margin(t = 0, r = -10, b = 0, l = 0))
  ) +
  scale_fill_manual(values=cbPalette)

g3 <- g0 +
  geom_beeswarm(aes(x=type, y=value, fill=type), shape=21, colour="grey40", cex=1.2, size=0.7) +
  #geom_boxplot(aes(x=type, y=value), fill=NA, colour="grey70", width=0.6, outlier.shape=NA) +
  scale_y_continuous(expand=c(0,0), limits=c(0, max(d$value)*1.03))

g4 <- g0 +
  geom_beeswarm(aes(x=type, y=value, fill=type), shape=21, colour="grey40", cex=2.2) +
  #geom_boxplot(aes(x=type, y=value), fill=NA, colour="grey70", width=0.6, outlier.shape=NA) +
  scale_y_log10(breaks=c(2, 5, 10, 20, 50, 100, 200, 500)) +
  annotation_logticks(sides="l") +
  theme(axis.ticks.y = element_blank())


g <- plot_grid(g1, g3, g2, g4, ncol=2, align="hv")
g

ggsave(paste0(fig, "linear_vs_logarithmic_2.png"), plot=g, device="png", width=6, height=5, dpi=300)

```


```{r error_bars, fig.width=12, fig.height=3}
set.seed(1410)
n1 <- 8
d1 <- data.frame(
  x = 1:n1,
  y = n1 - 1:n1 + rnorm(n1, 0, 1.5),
  s = rnorm(n1, 0.8, 0.1)
)

g1 <- emptyBox("") +
  geom_errorbar(data=d1, aes(x=x, ymin=y-s, ymax=y+s), width=0.2) +
  geom_point(data=d1, aes(x=x, y=y))

n2 <- 5
d2 <- data.frame(
  x = 1:n2,
  y = 1:n2 + rnorm(n2, 0, 1.5),
  sy = rnorm(n2, 0.4, 0.1),
  sx = 0.3
)

g2 <- emptyBox("") +
  geom_errorbar(data=d2, aes(x=x, ymin=y-sy, ymax=y+sy), width=0.12) +
  geom_errorbarh(data=d2, aes(y=y, xmin=x-sx, xmax=x+sx), height=0.08) +
  geom_point(data=d2, aes(x=x, y=y), shape=22, fill="white", size=1.5)

n3 <- 30
d3 <- data.frame(
  x = 1:n3,
  y = sin(1.3 * 1:n3/n3) + rnorm(n3, 0, 0.03),
  s = 0.06
)
g3 <- emptyBox("") +
  geom_errorbar(data=d3, aes(x=x, ymin=y-s, ymax=y+s), width=0, colour="grey70") +
  geom_point(data=d3, aes(x=x, y=y), size=1.5)


n4 <- 5
d4 <- data.frame(
  x = 1:n4,
  y = rnorm(n4, 5, 1),
  s = rnorm(n4, 1, 0.1)
)
g4 <- emptyBox("") +
  geom_col(data=d4, aes(x=x, y=y), fill=fill.colour, colour="black") +
  geom_errorbar(data=d4, aes(x=x, ymin=y-s, ymax=y+s), width=0.2) +
  scale_y_continuous(expand=c(0,0), limits=c(0, max(d4$y + d4$s) * 1.2))

g <- plot_grid(g1, g2, g3, g4, nrow=1)

g
ggsave(paste0(fig, "error_bars.png"), plot=g, device="png", width=9, height=2.3, dpi=300)
```

```{r boxplot}
n <- 250
d <- data.frame(
  x = 1,
  y = rnorm(n)
)

g <- ggplot(d) +
  theme_nothing() +
  geom_boxplot(aes(x,y), fill=fill.colour)

g
ggsave(paste0(fig, "boxplot.png"), plot=g, device="png", width=1.5, height=5, dpi=300)
```


```{r boxplot_examples}
set.seed(666)
n <- c(50, 30, 40, 20)
d <- data.frame(
  type = c(rep("WT", n[1]), rep("KO1", n[2]), rep("KO2", n[3]), rep("KO3", n[4])),
  value = c(rnorm(n[1], 20, 5), rnorm(n[2], 25, 3), rnorm(n[3], 30, 4), rnorm(n[4], 18, 7))
)
dm <- data.frame(
  x = "WT",
  y = median(d[d$type == "WT", "value"])
)

g1 <- ggplot() +
  theme_classic() +
  theme(legend.position = "none", plot.margin = margin(r=30)) +
  geom_boxplot(data=dm, aes(x=x, middle=y, ymin=y, lower=y, upper=y, ymax=y), stat="identity", width=0.7, lwd=0.6, fatten=0) +
  geom_beeswarm(data=d[d$type == "WT", ], aes(type, value), size=0.8, cex=2.5, shape=21, fill=fill.colour) +
  geom_boxplot(data=d[d$type != "WT", ], aes(type, value, fill=type)) +
  scale_fill_manual(values=cbPalette) +
  labs(x=NULL, y="Value")


fastq <- read.table("../data/fastq_quality.txt", sep="", header=TRUE)
g2 <- ggplot(fastq) +
  theme_classic() +
  theme(axis.title.y.right = element_blank(), axis.title.x.top = element_blank()) +
  geom_boxplot(aes(x=Base, middle=Median, ymin=X10thPercentile, lower=LowerQuartile, upper=UpperQuartile, ymax=X90thPercentile), stat="identity", fill=fill.colour, width=0.7, fatten=0.5, lwd=0.3) +
  scale_y_continuous(expand=c(0,0), limits=c(0,41.5), sec.axis = dup_axis()) +
  scale_x_continuous(breaks=c(1, seq(5,50,5)), sec.axis = dup_axis()) +
  labs(x="Position in read (bp)", y="Sequence quality")

g <- plot_grid(g1, g2, nrow=1, rel_widths = c(1,2.2), align="h")
ggsave(paste0(fig, "boxplot_examples.png"), plot=g, device="png", width=7, height=3, dpi=300)
```



```{r barplot_example_1}
d <- data.frame(
  n = c(101, 98, 112, 100, 104, 89, 99, 100),
  s = c(86, 23, 67, 55, 95, 12, 34, 34),
  cond = rep(c("WT", "KO1", "KO2", "KO3"), 2),
  treat = c(rep("DMSO", 4), rep("DD342", 4))
)
d$p <- d$s / d$n
d$cond <- relevel(d$cond, "WT")
d$treat <- relevel(d$treat, "DMSO")

P <- lapply(1:nrow(d), function(i) {
  prop.test(d$s[i], d$n[i])$conf.int
})
lim <- setNames(as.data.frame(do.call(rbind, P)), c("lo", "up"))
d <- cbind(d, lim)

g <- ggplot(d, aes(x=cond, y=p, fill=treat)) +
  theme_classic() +
  theme(legend.position = "bottom") +
  geom_bar(position=position_dodge(0.8), stat="identity", colour="black", width=0.8) +
  geom_errorbar(aes(ymin=lo, ymax=up), width=.2, position=position_dodge(0.8)) +
  scale_fill_manual(values=c(fill.colour, fill.colour.dark), name="Treatment") +
  scale_y_continuous(expand=c(0,0), limits=c(0, max(d$up) * 1.03)) +
  labs(x=NULL, y="Proportion of cells")

g
ggsave(paste0(fig, "barplot_example1.png"), plot=g, device="png", width=4, height=3, dpi=300)
```

```{r barplot_example_2}
set.seed(1)
x <- c(runif(500), abs(rnorm(100, 0, 0.04)))

brks <- seq(0, 1, 0.1)
g <- ggplot(data.frame(x=x), aes(x=x)) +
  theme_classic() +
  theme(axis.title.y.right = element_text(margin=margin(l=8))) +
  theme(plot.margin = margin(l=10, r=12, t=10)) +
  geom_histogram(breaks=brks, fill=fill.colour, colour="black") +
  labs(x="P-value", y="Count") +
  scale_x_continuous(expand=c(0,0), breaks=seq(0,1,0.2)) +
  scale_y_continuous(expand=c(0,0), limits=c(0, 150), sec.axis = sec_axis(~./60, "Density"))

g
ggsave(paste0(fig, "barplot_example2.png"), plot=g, device="png", width=4.5, height=3.5, dpi=300)
```

```{r bad_bar_plots}
d <- data.frame(
  x = c("Control", "Treatment"),
  y = c(400, 800)
)

bar1 <- function(d, lims=c(0, 900), ylab="Count") {
  ggplot(d, aes(x, y)) +
    theme_classic() +
    geom_col(fill=fill.colour, colour="black") +
    coord_cartesian(ylim=lims, xlim=c(0.3,2.8), expand=FALSE) +
    labs(x=NULL, y=ylab)
}
g1 <- bar1(d, lims=c(0, 900))
g2 <- bar1(d, lims=c(350, 850))
g <- plot_grid(g1, g2, nrow=1, align="h")
g

ggsave(paste0(fig, "badbar_baseline.png"), plot=g, device="png", width=5, height=2.5, dpi=300)

d$y <- log10(d$y)

g1 <- bar1(d, lims=c(0, 3), ylab=expression(log[10]~count))
g2 <- bar1(d, lims=c(2.2, 3), ylab=expression(log[10]~count))
g <- plot_grid(g1, g2, nrow=1, align="h")
g

ggsave(paste0(fig, "badbar_log.png"), plot=g, device="png", width=5, height=2.5, dpi=300)
```

```{r barplot_problems_1}
set.seed(1383)
n <- 20
M <- c(1.4, 1.35, 1.25, 1.25, 1.23, 1.25)
d <- lapply(1:length(M), function(i) {
  data.frame(sample=i, speed=rnorm(n, M[i], 0.15))
})
d <- do.call(rbind, d)
dm <- d %>% group_by(sample) %>% summarise(m=mean(speed), se=sd(speed) / sqrt(n()))

g0 <- ggplot() +
  theme_classic() +
  scale_x_continuous(breaks=seq(1:length(M))) +
  labs(x="Sample", y = ~ "Speed ("*mu*m/min*")")

wdth <- 2.5
hght <- 2.5

g1 <- g0 +
  geom_col(data=dm, aes(x=sample, y=m), fill=fill.colour, colour="black") + 
  geom_errorbar(data=dm, aes(x=sample, ymin=m-se, ymax=m+se), width=0.2) +
  scale_y_continuous(expand=c(0,0), limits=c(0, max(dm$m+dm$se)*1.03))

g1
ggsave(paste0(fig, "bar_problem_1.png"), plot=g1, device="png", width=wdth, height=hght, dpi=300)

g2 <- g0 +
  geom_point(data=dm, aes(x=sample, y=m), colour="black") + 
  geom_errorbar(data=dm, aes(x=sample, ymin=m-se, ymax=m+se), width=0.2)
g2
ggsave(paste0(fig, "bar_problem_2.png"), plot=g2, device="png", width=wdth, height=hght, dpi=300)

d$samplef <- as.factor(d$sample)
g3 <- g0 +
  theme(legend.position = "none") +
  geom_boxplot(data=dm, aes(x=sample, middle=m, ymin=m, lower=m, upper=m, ymax=m), stat="identity", width=0.5, lwd=0.5, fatten=0) +
  geom_beeswarm(data=d, aes(x=sample, y=speed, fill=samplef), shape=21, colour="black", cex=1.8, size=0.8) +
  scale_fill_manual(values=cbPalette)
g3
ggsave(paste0(fig, "bar_problem_3.png"), plot=g3, device="png", width=wdth, height=hght, dpi=300)
```

```{r barplot_problems_2}
set.seed(557)
t <- seq(0, 16, 2)
n <- length(t)
y1 <-  40 - 2 * t + rnorm(n, 0, 2)
s1 <-  rnorm(n, 2, 0.3)
y2 <-  3 + t + rnorm(n, 0, 1)
s2 <-  rnorm(n, 2, 0.3)

d <- data.frame(
  time = c(t, t),
  type = c(rep("A", n), rep("B", n)),
  y = c(y1, y2),
  s = c(s1, s2)
)

wdth <- 3.5
hght <- 2.5
g0 <- ggplot(d, aes(x=time, y=y)) +
  theme_classic() +
  theme(legend.position = "none") +
  labs(x="Time (h)", y = ~ "Distance ("*mu*m*")") +
  scale_y_continuous(expand=c(0,0), limits=c(0, max(d$y + d$s) * 1.03)) 

g1 <- g0 +
  geom_errorbar(aes(ymin=y-s, ymax=y+s, group=type), width=.5, position=position_dodge(1.5)) +
  geom_bar(aes(fill=type), position=position_dodge(1.5), stat="identity", colour="black", width=1.5) +
  scale_fill_manual(values=c("black", "white"), name="Treatment")
g1

ggsave(paste0(fig, "bar_problem_4.png"), plot=g1, device="png", width=wdth, height=hght, dpi=300)

g2 <- g0 +
  geom_errorbar(aes(ymin=y-s, ymax=y+s, group=type), width=.5) +
  geom_pointpath(aes(fill=type, group=type), shape=21, colour="black", linecolour="grey70") +
  scale_fill_manual(values=c("black", "white"), name="Treatment")

g2

ggsave(paste0(fig, "bar_problem_5.png"), plot=g2, device="png", width=wdth, height=hght, dpi=300)
```


```{r dynamite_plots}
d <- data.frame(
  type = c("WT", "T1", "T2"),
  value = c(100, 87, 59),
  lo = c(NA, 61, 48),
  up = c(NA, 98, 69)
)
d$type <- relevel(d$type, "WT")

g <- ggplot(d, aes(x=type, y=value, ymin=lo, ymax=up)) +
  theme_classic() +
  labs(x=NULL, y="Percentage") +
  scale_y_continuous(expand=c(0,0), limits=c(0, 105))

g1 <- g +
  geom_errorbar(width=.5) +
  geom_col(fill="black")

g2 <- g +
  geom_col(fill="grey60") +
  geom_errorbar(width=.5)

g3 <- ggplot(d[2:3, ], aes(x=type, y=value/100, ymin=lo/100, ymax=up/100)) +
  theme_classic() +
  labs(x=NULL, y="WT fraction") +
  geom_hline(yintercept = 1, colour="grey60") +
  geom_errorbar(width=.2) +
  geom_point()

g1
g2
g3

ggsave(paste0(fig, "dynamite_1.png"), plot=g1, device="png", width=2, height=4, dpi=300)
ggsave(paste0(fig, "dynamite_2.png"), plot=g2, device="png", width=2, height=4, dpi=300)
ggsave(paste0(fig, "dynamite_3.png"), plot=g3, device="png", width=2, height=2, dpi=300)

```

