---
title: "09 ANOVA"
output:
  html_document:
    css: tabbed_notebook.css
    fig_width: 3
    fig_height: 3
params: 
  output_dir: "../output"
---

```{r setup, echo=FALSE}
root <- "09_anova"
source("../R/setup.R")
knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  echo = FALSE,
  cache = TRUE,
  cache.path = paste0("../cache/", root),
  fig.path = paste0("../cache/", root)
)
fig <- paste0("../fig/", root, "/")
if(!dir.exists(fig)) dir.create(fig)
```



```{css echo=FALSE}
pre code, pre, code {
  white-space: pre !important;
  overflow-x: scroll !important;
  word-break: keep-all !important;
  word-wrap: initial !important;
}
```

```{r aov_results}
aovResults <- function(dat) {
  fit <- aov(Mass ~ Country, data=dat)
  res <- summary(fit)
  MS.w <- res[[1]]$`Mean Sq`[2]
  MS.b <- res[[1]]$`Mean Sq`[1]
  p <- res[[1]]$`Pr(>F)`[1]
  F <- res[[1]]$`F value`[1]
  list(MS.w=MS.w, MS.b=MS.b, F=F, p=p)
}
```



```{r read_mice_data}
countries <- c("English", "Scottish", "Welsh", "N.Irish")

mice1 <- read.table("../data/mice_1way.txt", header=TRUE)
mice1$Country <- factor(mice1$Country, levels=countries)

mice2 <- read.table("../data/mice_2way.txt", header=TRUE)
mice2$Country <- factor(mice2$Country, levels=countries)
mice2$Colour <- factor(mice2$Colour, levels=c("White", "Black"))
```

```{r plot_mice_box_function}
plotMiceBox <- function(mice, seed=111, limits=NULL) {
  set.seed(seed)
  g <- ggplot(mice, aes(x=Country, y=Mass)) +
    theme_classic() +
    theme(legend.position = "none") +
    geom_boxplot(aes(fill=Country), alpha=0.5, colour="grey50", outlier.shape = NA) +
    scale_fill_manual(values=british.palette) +
    #geom_jitter(width=0.15, height=0) +
    geom_beeswarm(cex=2, size=1.5, shape=21, fill="grey20") +
    labs(x="", y="Body mass (g)")
  if(!is.null(limits)) g <- g + ylim(limits)
  g
}
```


```{r mice_1way_plot, fig.width=4, fig.height=3}
g <- plotMiceBox(mice1) 
g 

ggsave(paste0(fig, "mice_1way.png"), plot=g, device="png", width=3.5, height=3.5, dpi=300)
```


```{r variance_within_between, fig.width=6}
set.seed(23143)
makeVar <- function(M, S=5, n=20) {
  stopifnot(length(M) == length(countries))
  X <- sapply(1:length(M), function(i) rnorm(n, M[i], S))
  colnames(X) <- countries
  d <- reshape2::melt(X, varnames=c("i", "Country"), value.name="Mass")
}

plotWB <- function(d, maxy=40) {
  aov <- aovResults(d)
  d$x <- as.numeric(d$Country)
  dm <- d %>% group_by(Country) %>% summarise(M=mean(Mass), SD=sd(Mass)) %>% mutate(x=as.numeric(Country))
  vb <- data.frame(x=5, M=20, SD=sqrt(aov$MS.b))
  ggplot() +
    theme_classic() +
    theme(legend.position = "none") +
    geom_beeswarm(data=d, aes(x=x, y=Mass, fill=Country), colour="grey70", cex=1.4, size=0.9, shape=21) +
    scale_fill_manual(values=british.palette) +
    scale_y_continuous(expand=c(0,0), limits=c(0, maxy)) +
    geom_errorbar(data=dm, aes(x=x, ymin=M-SD, ymax=M+SD), width=0.4) +
    geom_point(data=dm, aes(x=x, y=M), size=2, shape=21, fill="white") +
    geom_errorbar(data=vb, aes(x=x, ymin=M-SD, ymax=M+SD), width=0.4, colour="grey50") +
    labs(x=NULL, y="Body mass (g)") +
    scale_x_continuous(breaks=1:4, labels=countries)
}

v.same <- makeVar(c(20, 20, 20, 20))
v.diff <- makeVar(c(20, 28, 20, 20))
max(v.diff$Mass)
g1 <- plotWB(v.same)
g2 <- plotWB(v.diff)
g <- plot_grid(g1, g2, nrow=1)
g

ggsave(paste0(fig, "variance_between_within.png"), plot=g, device="png", width=5.8, height=3, dpi=300)


```


```{r variance_reminder, fig.width=3, fig.height=2}
dat <- subset(mice1, Country == "English")
dat <- data.frame(
  i = seq_along(dat$Mass),
  y = dat$Mass
)
M <- mean(dat$y)
dat$ym <- M

g <- ggplot(dat) +
  theme_classic() +
  geom_segment(aes(x=i, xend=i, y=ym, yend=y), colour="grey60") +
  geom_hline(yintercept = M, linetype="dotted", colour="grey50") +
  geom_point(aes(x=i, y=y)) +
  scale_x_continuous(breaks=dat$i, labels=dat$i) +
  labs(x="Data point", y="Body mass (g)")
g

ggsave(paste0(fig, "variance.png"), plot=g, device="png", width=3.5, height=2.5, dpi=300)
```

```{r get_means_function}
getMeans <- function(mice, value="Mass") {
  width <- 0.6
  M <- tapply(mice[, value], mice$Country, mean)
  L <- tapply(mice$Country, mice$Country, length)
  mice$grand.mean <- mean(mice[, value])
  mice$Mean <- M[mice$Country]
  mice$N <- L[mice$Country]
  mice$group <- as.integer(mice$Country)
  mice$n <- unlist(tapply(mice$Country, mice$Country, seq_along))
  mice$x <- as.integer(mice$Country) + width*(mice$n - mice$N/2 - 1/2) / (mice$N - 1)
  means <- data.frame(x=as.numeric(seq_along(M)), mean=M, country=names(M))
  list(mice=mice, means=means)  
}
```


```{r prepare_mice}
m <- getMeans(mice1)
mice1 <- m$mice
means <- m$means
```

```{r plot_variance_function}
plotVariance <- function(mice, means, within=TRUE) {
  gm <- mice$grand.mean[1]
  width <- 0.6
  g <- ggplot(mice) + theme_classic()
  if(within) {
    g <- g + geom_segment(aes(x=x, xend=x, y=Mean, yend=Mass), colour="grey70")
  } else {
    g <- g +
      geom_line(data=data.frame(x=c(1-width/2,4+width/2), y=c(gm, gm)), aes(x,y), linetype="dotted") +
      geom_segment(aes(x=x, xend=x, y=grand.mean, yend=Mean), colour="grey70")
  }
  g <- g +
    geom_segment(data=means, aes(x=x-width/2, xend=x+width/2, y=mean, yend=mean, colour=country)) +
    geom_point(aes(x=x, y=Mass, fill=Country), colour="grey30", shape=21, size=1.8) +
    theme(legend.position = "none", axis.ticks.x = element_blank()) +
    scale_x_continuous(breaks=c(1,2,3,4), labels=levels(mice1$Country)) +
    labs(x="", y="Body mass (g)") +
    scale_colour_manual(values=british.palette) +
    scale_fill_manual(values=british.palette)
  g
}
```

```{r variance_within, fig.width=4, fig.height=3}
g1 <- plotVariance(mice1, means, within=TRUE)
g2 <- plotVariance(mice1, means, within=FALSE)
g1 
g2 
ggsave(paste0(fig, "variance_within.png"), plot=g1, device="png", width=4.5, height=4, dpi=300)
ggsave(paste0(fig, "variance_between.png"), plot=g2, device="png", width=4.5, height=4, dpi=300)
```

```{r f_dist_generate}
set.seed(33)
L <- tapply(mice1$Country, mice1$Country, length)
F.gen <- lapply(1:100000, function(i) {
  x <- lapply(L, function(n) rnorm(n, 20, 5))
  dat <- data.frame(
    Country = mice1$Country,
    Mass = unlist(x)
  )
  res <- aovResults(dat)
  res$F
})
F.gen <- unlist(F.gen)
```

```{r f_dist_plot, fig.width=3, fig.height=2.5}
g <- plotOneDist(F.gen, "F", "", c(0, 6), df, 3, 30)
g 

ggsave(paste0(fig, "mice_1way_F.png"), plot=g, device="png", width=3.5, height=3.5, dpi=300)
```


```{r generate_no_effect}
set.seed(8)
L <- tapply(mice1$Country, mice1$Country, length)
repeat {
  x <- lapply(L, function(n) rnorm(n, 20, 5))
  dat <- data.frame(
    Country = mice1$Country,
    Mass = unlist(x)
  )
  res <- aovResults(dat)
  if(res$F < 1.1 && res$F > 0.9 && res$p > 0.1) break
}
res
```

```{r plot_no_effect, fig.width=4, fig.height=3}
g <- plotMiceBox(dat)
g

ggsave(paste0(fig, "mice_1way_no_effect.png"), plot=g, device="png", width=3.5, height=3.5, dpi=300)
```



```{r mice_colour, fig.width=4, fig.height=3}
g1 <- plotMiceBox(subset(mice2, Colour=="White"), limits=c(0,42))
g2 <- plotMiceBox(subset(mice2, Colour=="Black"), limits=c(0,42))
g1
g2

ggsave(paste0(fig, "mice_white.png"), plot=g1, device="png", width=3.5, height=3.5, dpi=300)
ggsave(paste0(fig, "mice_black.png"), plot=g2, device="png", width=3.5, height=3.5, dpi=300)
```

```{r read_time_course}
tc <- readRDS("../data/time_course.rds")
norm <- tc[1:8, "Mass"]
tc$nMass <- tc$Mass / norm
tcm <- tc %>% group_by(Treatment, Time) %>% summarise(M = mean(Mass), SE = sd(Mass) / sqrt(n()), nM = mean(nMass), nSE = sd(nMass) / sqrt(n()))
```


```{r time_course_plot, fig.width=3, fig.height=3}
g0 <- ggplot() +
  theme_classic() +
  scale_colour_manual(values=cbPalette) +
  scale_fill_manual(values=cbPalette) +
  scale_shape_manual(values=c(21, 24)) +
  labs(x="Time (week)", y="Body mass (g)") +
  theme(legend.position = "none")
  
ps <- 1.5
g1 <- g0 + 
  geom_line(data=tc, aes(x=Time, y=Mass, colour=Treatment, group=Course), alpha=0.3) +
  geom_point(data=tc, aes(x=Time, y=Mass, fill=Treatment, shape=Treatment), size=ps) +
  ylim(0, 36)
g2 <- g0 + 
  geom_line(data=tcm, aes(x=Time, y=M, colour=Treatment, group=Treatment), alpha=0.3) +
  geom_point(dat=tcm, aes(x=Time, y=M, fill=Treatment, shape=Treatment), size=ps) +
  geom_errorbar(data=tcm, aes(x=Time, ymin=M-SE, ymax=M+SE, colour=Treatment), width=0.2) +
  ylim(0, 36)
g3 <- g0 +  
  geom_line(data=tc, aes(x=Time, y=nMass, colour=Treatment, group=Course), alpha=0.3) +
  geom_point(data=tc, aes(x=Time, y=nMass, fill=Treatment, shape=Treatment), size=ps) +
  labs(x="Time (week)", y="Normalized body mass")
g4 <- g0 + 
  geom_line(data=tcm, aes(x=Time, y=nM, colour=Treatment, group=Treatment), alpha=0.3) +
  geom_point(data=tcm, aes(x=Time, y=nM, fill=Treatment, shape=Treatment), size=ps) +
  geom_errorbar(data=tcm, aes(x=Time, ymin=nM-nSE, ymax=nM+nSE, colour=Treatment), width=0.2) +
  labs(x="Time (week)", y="Normalized body mass")

g1
g2
g3
g4

ggsave(paste0(fig, "time_course.png"), plot=g1, device="png", width=3, height=2.5, dpi=300)
ggsave(paste0(fig, "time_course_mean.png"), plot=g2, device="png", width=3, height=2.5, dpi=300)
ggsave(paste0(fig, "time_course_norm.png"), plot=g3, device="png", width=3, height=2.5, dpi=300)
ggsave(paste0(fig, "time_course_mean_norm.png"), plot=g4, device="png", width=3, height=2.5, dpi=300)
```


```{r area_under_curve_function}
area <- function(x, y) {
  n <- length(x)
  stopifnot(length(y) == n)
  d <- x[2:n] - x[1:(n-1)]
  h <- (y[2:n] + y[1:(n-1)]) / 2
  sum(d * h)
}

areaData <- function(dat, t1, t2) {
  courses <- unique(dat$Course)
  P <- lapply(courses, function(course) {
    d <- subset(dat, Course == course & Time >= t1 & Time <= t2)
    a <- area(d$Time, d$Mass)
    t <- as.character(d$Treatment[1])
    data.frame(Course=course, Treatment=t, Area=a)
  })
  do.call(rbind, P)
}

areaPlot <- function(d) {
  #d[d$Treatment == "Untreated", "Treat"] <- "CTRL"
  #d[d$Treatment == "Treated", "Treat"] <- "Treat"
  #d$Treat <- factor(d$Treat, levels=c("CTRL", "Treat"))
  ggplot(d, aes(x=Treatment, y=Area, fill=Treatment, shape=Treatment)) +
    theme_classic() +
    theme(legend.position = "none") +
    #geom_boxplot(aes(fill=Treat), alpha=0.5, outlier.shape = NA) +
    scale_fill_manual(values=cbPalette) +
    scale_shape_manual(values=c(21, 24)) +
    #geom_jitter(width=0.15, height=0) +
    geom_beeswarm(cex=5, size=1.5, size=1.8) +
    labs(x=NULL, y=NULL) +
    scale_y_continuous(expand=c(0, 0), limits=c(0, 290)) +
    scale_x_discrete(labels=c("CTRL", "Treat"))
}
```



```{r area_plot, fig.width=2, fig.height=3}
d1 <- areaData(tc, 0, 10) 
g1 <- areaPlot(d1)
g1 
t.test(d1[d1$Treatment == "Untreated", "Area"], d1[d1$Treatment == "Treated", "Area"])

d2 <- areaData(tc, 6, 10)
g2 <- areaPlot(d2)
g2
t.test(d2[d2$Treatment == "Untreated", "Area"], d2[d2$Treatment == "Treated", "Area"])

d3 <- areaData(tc, 0, 5)
g3 <- areaPlot(d3)
g3
t.test(d3[d3$Treatment == "Untreated", "Area"], d3[d3$Treatment == "Treated", "Area"])


ggsave(paste0(fig, "area_diff.png"), plot=plot_grid(g1, g2, g3, ncol=3), device="png", width=4, height=3.5, dpi=300) 
```

```{r anova2_plot_function}
plotAnova2 <- function(mice, ylim=c(0,40), text.size=10) {
  grand.mean <- mean(mice$Mass)
  mice.gr <- mice %>% group_by(Country, Colour) %>% summarise(M = mean(Mass))

  g1 <- ggplot(mice, aes(x=1, y=Mass)) +
    theme_classic() +
    facet_grid(Colour ~ Country, switch="both") +
    geom_hline(yintercept = grand.mean, linetype = "dotted", size=0.3) +
    #geom_boxplot(aes(fill=Country), alpha=0.5, outlier.shape = NA, width=0.7) +
    scale_fill_manual(values=british.palette) +
    geom_beeswarm(aes(fill=Country), cex=6.5, size=1.5, shape=21) +
    labs(x="", y="") +
    ylim(ylim) +
    xlim(0, 2) +
    theme(
      legend.position = "none",
      strip.background = element_blank(),
      strip.text = element_text(size=text.size),
      panel.spacing = unit(0, "cm"),
      panel.border = element_rect(fill=NA),
      axis.ticks = element_blank(),
      axis.text = element_blank(),
      axis.line = element_blank()
    )
  
  g2 <- ggplot(mice.gr, aes(x=Country, y=M, group=Colour, colour=Colour)) +
    theme_classic() +
    geom_line(aes(group=Colour)) +
    geom_point(aes(fill=Colour), size=2, shape=22) +
    labs(x="", y="") +
    ylim(ylim) +
    geom_hline(yintercept = grand.mean, linetype = "dotted", size=0.3) +
    scale_colour_manual(values=c("grey60", "black")) +
    scale_fill_manual(values=c("white", "black")) +
    scale_x_discrete(position = "top") +
    theme(
      panel.border = element_rect(colour="black", linetype="solid", fill=NA),
      legend.position = "none",
      axis.ticks = element_blank(),
      axis.text.y = element_blank(),
      panel.spacing = unit(0, "cm"),
      axis.line = element_blank(),
      axis.text = element_text(size=text.size),
      plot.margin = unit(c(-0.5,0,0,0),"cm")
    )
  
  g3 <- ggplot(mice.gr, aes(x=Colour, y=M, group=Country, colour=Country)) +
    theme_classic() +
    geom_line(aes(group=Country)) +
    geom_point(aes(colour=Country, fill=Country), size=2, shape=22) +
    labs(x="", y="") +
    ylim(ylim) +
    geom_hline(yintercept = grand.mean, linetype = "dotted", size=0.3) +
    scale_colour_manual(values=british.palette) +
    scale_fill_manual(values=british.palette) +
    scale_x_discrete(position = "bottom") +
    theme(
      panel.border = element_rect(colour="black", linetype="solid", fill=NA),
      legend.position = "none",
      axis.ticks = element_blank(),
      axis.text.y = element_blank(),
      panel.spacing = unit(0, "cm"),
      axis.line = element_blank(),
      axis.text = element_text(size=text.size),
      plot.margin = unit(c(0,0,0.6,0),"cm")
    )
  
  left_col <- g1
  right_col <- plot_grid(g2, g3, ncol=1, rel_heights = c(1, 1.33))
  
  plot_grid(left_col, right_col, ncol=2, rel_widths = c(1, 0.6))
}
```

```{r plot_anova2}
g <- plotAnova2(mice2)
g 

ggsave(paste0(fig, "mice_2way.png"), plot=g, device="png", width=6, height=3.5, dpi=300)
```


```{r generate_mice2_function}
rep.row<-function(x,n){
   matrix(rep(x,each=n),nrow=n)
}
rep.col<-function(x,n){
   matrix(rep(x,each=n), ncol=n, byrow=TRUE)
}

generateMice2 <- function(
  A = matrix(c(0, 0, 0, 0), nrow=1),
  B = matrix(c(0, 0), ncol=1), 
  G = rbind(c(0,0,0,0), c(0,0,0,0)),
  countries = c("English", "Scottish", "Welsh", "N.Irish"),
  colours = c("White", "Black"),
  m=20, s=5, n=10) {
  
  nr <- nrow(G)
  nc <- ncol(G)
  stopifnot(ncol(A) == nc && nrow(B) == nr)
  
  AA <- rep.row(A, nr)
  BB <- rep.col(B, nc)
  
  P <- lapply(1:n, function(i) {
    X <- m + AA + BB + G + rnorm(8, 0, s)
    rownames(X) <- colours
    colnames(X) <- countries
    reshape2::melt(X, varnames=c("Colour", "Country"), value.name="Mass")
  })
  do.call(rbind, P)
}
```


```{r aov2_results_function}
aov2Results <- function(dat) {
  mice.lm <- lm(Mass ~ Country + Colour + Country*Colour, dat)
  aov <- anova(mice.lm)
  p.col <- aov[5]$`Pr(>F)`[1]
  p.row <- aov[5]$`Pr(>F)`[2]
  p.int <- aov[5]$`Pr(>F)`[3]
  list(p.col=p.col, p.row=p.row, p.int=p.int)
}
```

```{r anova2_hyp}
# all three true
set.seed(1001)
X1 <- generateMice2()
g1 <- plotAnova2(X1)
g1
aov2Results(X1)

# columns not equal
set.seed(2000)
X2 <- generateMice2(A=matrix(c(0, 10, -10, 0), nrow=1))
g2 <- plotAnova2(X2)
g2
aov2Results(X2)

# rows not equal
set.seed(3001)
X3 <- generateMice2(B=matrix(c(10, -10), ncol=1))
g3 <- plotAnova2(X3)
g3
aov2Results(X3)

# interaction
set.seed(4003)
X4 <- generateMice2(G=rbind(c(-10, 10, 0, 0), c(10, -10, 0, 0)))
g4 <- plotAnova2(X4)
g4
aov2Results(X4)

ggsave(paste0(fig, "anova2_true.png"), plot=g1, device="png", width=6, height=3.5, dpi=300)
ggsave(paste0(fig, "anova2_cols.png"), plot=g2, device="png", width=6, height=3.5, dpi=300)
ggsave(paste0(fig, "anova2_rows.png"), plot=g3, device="png", width=6, height=3.5, dpi=300)
ggsave(paste0(fig, "anova2_inter.png"), plot=g4, device="png", width=6, height=3.5, dpi=300)
```


```{r simple_anova_plot_function}
simpleAnovaPlot <- function(dat, title="") {
  colnames(dat) <- c("Drug", "Placebo")
  rownames(dat) <- c("Male", "Female")
  m <- reshape2::melt(t(dat), varnames=c("Treatment", "Gender"), value.name="Score")
  ggplot(m, aes(x=Gender, y=Score, group=Treatment)) +
    geom_line(aes(colour=Treatment)) +
    geom_point(aes(shape=Treatment, colour=Treatment)) +
    scale_colour_manual(values=cbPalette) +
    ylim(c(0,30)) +
    theme(legend.position = "none") +
    labs(title=title)
}
```


```{r simple_anova, fig.width=2, fig.height=2}
dat1 <- rbind(c(20, 5), c(20, 5))
g1 <- simpleAnovaPlot(dat1, "Drug effect")
g1
dat2 <- rbind(c(15, 5), c(25, 15))
g2 <- simpleAnovaPlot(dat2, "Drug and gender effect")
g2
dat3 <- rbind(c(25, 5), c(10, 5))
g3 <- simpleAnovaPlot(dat3, "Interaction effect")
g3

g <- plot_grid(g1, g2, g3, ncol=3)

ggsave(paste0(fig, "simple_anova.png"), plot=g, device="png", width=8, height=3, dpi=300)

```