---
title: "12 Multiple test corrections"
output:
  html_document:
    css: tabbed_notebook.css
    fig_width: 3
    fig_height: 3
params: 
  output_dir: "../output"
---

```{r setup, echo=FALSE}
root <- "12_multiple_test_corrections"
source("../R/setup.R")
library(boot)
library(pwr)
library(parallel)
library(qvalue)
knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  echo = FALSE,
  cache = TRUE,
  cache.path = paste0("../cache/", root),
  fig.path = paste0("../cache/", root)
)
fig <- paste0("../fig/", root, "/")
if(!dir.exists(fig)) dir.create(fig)
```

```{css echo=FALSE}
pre code, pre, code {
  white-space: pre !important;
  overflow-x: scroll !important;
  word-break: keep-all !important;
  word-wrap: initial !important;
}
```

```{r gene_example}
k <- 1:10000
de <- data.frame(
  gene_id = sprintf("GENE%05d", k),
  p.value = runif(10000)
)
myKable(de[1:20,])
```

```{r fwer, fig.width=3, fig.height=3}
k <- 1:30
alpha <- 0.05
dat <- data.frame(
  k = k,
  pm = 1 - (1 - alpha)^k,
  pmc = 1 - (1 - alpha/k)^k
)

g0 <- ggplot(dat) +
  theme_classic() +
  geom_point(aes(k, pm), fill="red", colour="black", shape=21, size=2) +
  labs(x="m", y="FWER") +
  geom_hline(yintercept = alpha) +
  scale_x_continuous(expand=c(0,0), limits=c(0, 31), breaks=c(1,5,10,15,20,25,30)) +
  scale_y_continuous(expand=c(0,0), limits=c(0, 0.8), breaks=seq(0,1,0.2))

p20 <- 1 - (1 - alpha)^20
seg <- data.frame(
  x = c(0, 20, 20),
  y = c(p20, p20, 0)
)
g1 <- g0 
  #geom_line(data=seg, aes(x, y), linetype="dotted")

g2 <- g0 +
  geom_point(aes(k, pmc), fill="blue", colour="black", shape=21, size=2)

g1
g2

ggsave(paste0(fig, "fwer.png"), plot=g1, device="png", width=3.5, height=3, dpi=300)
ggsave(paste0(fig, "fwer_bonferroni.png"), plot=g2, device="png", width=3.5, height=3, dpi=300)
```

```{r generate_two_data}
set.seed(110)
h0 <- rnorm(5*970, 20, 5)
h1 <- rnorm(5*30, 40, 5)
mdat <- data.frame(
  Value = c(h0, h1),
  Hypothesis = c(rep(0, 5*970), rep(1, 5*30))
)
mdat$Hypothesis <- factor(mdat$Hypothesis, levels=c(1,0))
```

```{r read_two_p_data}
# this are tweaked p-values generated by Perl script
pdat <- read.table("../data/multi_two_hypotheses.txt", header=TRUE, sep="\t")
pdat$Hypothesis <- factor(pdat$Hypothesis, levels=c(1,0))
```

```{r plot_two_dist, fig.width=3, fig.height=3}
brks <- seq(0, 60, 1)
g <- ggplot(mdat, aes(x=Value)) +
  theme_classic() +
  geom_histogram(aes(fill=Hypothesis), breaks=brks, position="identity") +
  scale_fill_manual(values=c(fill.colour.dark, fill.colour.mid)) +
  labs(x = "Body mass (g)", y="Frequency") +
  theme(legend.position = "none") +
  scale_y_continuous(expand=c(0,0)) +
  scale_x_continuous(expand=c(0,0))
g 

ggsave(paste0(fig, "test_data_dist.png"), plot=g, device="png", width=3.5, height=3, dpi=300)
```


```{r plot_p_two_dist, fig.width=3, fig.height=3}
brks <- seq(0, 1, 0.025)
g <- ggplot(pdat, aes(x=p.value)) +
  theme_classic() +
  geom_histogram(aes(fill=Hypothesis), breaks=brks, position="stack") +
  scale_fill_manual(values=c(fill.colour.dark, fill.colour.mid)) +
  labs(x = "p-value", y="Frequency") +
  theme(legend.position = "none") +
  scale_y_continuous(expand=c(0,0)) +
  scale_x_continuous(expand=c(0,0), breaks=c(0, 0.2, 0.4, 0.6, 0.8, 1)) +
  geom_vline(xintercept = 0.05, linetype="dotted")
g 
 
ggsave(paste0(fig, "test_data_p_dist.png"), plot=g, device="png", width=3.5, height=2.5, dpi=300)
```


```{r p_table_function}
pTable <- function(dat, alpha=0.05) {
  FP <- sum(dat$Hypothesis==0 & dat$p.value <= alpha)
  TP <- sum(dat$Hypothesis==1 & dat$p.value <= alpha)
  TN <- sum(dat$Hypothesis==0 & dat$p.value > alpha)
  FN <- sum(dat$Hypothesis==1 & dat$p.value > alpha)
  m0=FP+TN
  m1=FN+TP
  list(FP=FP, TP=TP, TN=TN, FN=FN, P=FP+TP, N=TN+FN, m0=m0, m1=m1, FPR=FP/m0, FNR=FN/m1, FDR=FP/(FP+TP))
}

```

# Uncorrected data

```{r p_table}
pt <- pTable(pdat)
str(pt)
```

# Bonferroni correction

```{r p_table_bonferroni}
ptb <- pTable(pdat, alpha=0.05/nrow(pdat))
str(ptb)
```

```{r small_p_data}
m <- 5
k <- 1:m
alpha <- 0.05
sp <- data.frame(
  k = k,
  p = c(0.003, 0.005, 0.012, 0.038, 0.058),
  alpha = alpha,
  alpha_b = alpha / m,
  alpha_hb = alpha / (m - k + 1),
  alpha_bh = k * alpha / m
)
```


```{r small_p_table}
myKable(sp, digits=5) 
```

```{r small_p_plot, fig.width=3, fig.height=3}
sp1 <- rbind(sp, c(6, NA, alpha, alpha, alpha, alpha))

g <- ggplot(sp) +
  theme_classic() +
  geom_point(aes(x=k, y=p), shape=21, fill="red", colour="black", size=2) +
  labs(x="k", y="p-value") +
  scale_x_continuous(expand=c(0,0), limits=c(0.5, 5.5)) +
  scale_y_continuous(expand=c(0,0), limits=c(0, 0.06))

g <- g +
  geom_hline(yintercept = alpha, colour="darkgreen", linetype="dotted") +
  geom_hline(yintercept = alpha/m, colour="darkgreen", linetype="dotted") +
  annotate("text", x=0.7, y=0.053, label="Uncorrected", colour="darkgreen", size=3.2, hjust=0) +
  annotate("text", x=5.35, y=0.007, label="Bonferroni", colour="darkgreen", size=3.2, hjust=1)

g1 <- g +
  geom_step(data=sp1, aes(x=k-0.5, y=alpha_hb), colour="blue") +
  annotate("text", x=3.56, y=0.022, label="Holm-Bonferroni", colour="blue", size=3.2, hjust=0)


g2 <- g1 +
  geom_step(data=sp1, aes(x=k-0.5, y=alpha_bh), colour="red") +
  annotate("text", x=3.44, y=0.033, label="Benjamini-Hochberg", colour="red", size=3.2, hjust=1)

g1
g2 

ggsave(paste0(fig, "small_p_1.png"), plot=g1, device="png", width=3, height=2.5, dpi=300)
ggsave(paste0(fig, "small_p_2.png"), plot=g2, device="png", width=3, height=2.5, dpi=300)
```

```{r large_p_data}
m <- nrow(pdat)
k <- 1:m
alpha <- 0.05
lp <- data.frame(
  k = k,
  p = sort(pdat$p.value),
  Hypothesis = pdat$Hypothesis,
  alpha = alpha,
  alpha_b = alpha / m,
  alpha_hb = alpha / (m - k + 1),
  alpha_bh = k * alpha / m
)
lp$p.value <- lp$p
```

```{r big_p_plot, fig.width=4, fig.height=4}
hb_limit <- max(lp[lp$p <= lp$alpha_hb, "k"])
bh_limit <- max(lp[lp$p <= lp$alpha_bh, "k"])
lp$p.adj <-  p.adjust(lp$p, "BH")

g <- ggplot(lp) +
  theme_classic() +
  geom_point(aes(x=k, y=log10(p)), shape=21, fill="grey", colour="black", size=2) +
  
  labs(x="k", y="log p-value") +
  scale_x_continuous(expand=c(0,0), limits=c(0.5, 30.5), breaks=c(1,5,10,15,20,25,30)) +
  scale_y_continuous(expand=c(0,0), limits=c(-6, -2))

  
g1 <- g +
  geom_point(data=lp[1:hb_limit,], aes(x=k, y=log10(p)), shape=21, fill="red", colour="black", size=2) +
  geom_step(aes(x=k-0.5, y=log10(alpha_hb)), colour="blue", linetype="dashed", alpha=0.5) +
  annotate("text", x=30, y=-4.45, label="Holm-Bonferroni", colour="blue", size=3.2, hjust=1) +
  annotate("text", x=30, y=-4.15, label="Bonferroni", colour="darkgreen", size=3.2, hjust=1) +
  geom_hline(yintercept = log10(alpha/m), colour="darkgreen", linetype="solid") 


g2 <- g1 +
  geom_step(aes(x=k-0.5, y=log10(alpha_bh)), colour="red", linetype="solid", alpha=1) +
  annotate("text", x=14, y=-3, label="Benjamini-Hochberg", colour="red", size=3.2, hjust=1) +
  geom_vline(xintercept = bh_limit, colour="red", linetype="dashed") +
  geom_point(data=lp[1:bh_limit,], aes(x=k, y=log10(p)), shape=21, fill="red", colour="black", size=2)

g3 <- g +
  geom_point(data=lp[1:bh_limit,], aes(x=k, y=log10(p)), shape=21, fill="red", colour="black", size=2) +
  geom_point(aes(x=k, y=log10(p.adj)), shape=21, fill="grey", colour="black", size=2) +
  geom_point(data=lp[1:bh_limit,], aes(x=k, y=log10(p.adj)), shape=21, fill="red", colour="black", size=2) +geom_step(aes(x=k-0.5, y=log10(alpha_bh)), colour="red", linetype="solid", alpha=1) +
  #annotate("text", x=14, y=-3, label="Benjamini-Hochberg", colour="red", size=3.2, hjust=1) +
  #annotate("text", x=3, y=-1.1, label="0.05", colour="red", size=3.2, hjust=0) +
  scale_y_continuous(expand=c(0,0), limits=c(-6,0)) +
  geom_hline(yintercept = log10(0.05), colour="red")

g1 <- g1 + geom_vline(xintercept = hb_limit, colour="red", linetype="dashed")

g1 
g2
g3

ggsave(paste0(fig, "large_p_1.png"), plot=g1, device="png", width=4, height=3.5, dpi=300)
ggsave(paste0(fig, "large_p_2.png"), plot=g2, device="png", width=4, height=3.5, dpi=300)
ggsave(paste0(fig, "large_p_3.png"), plot=g3, device="png", width=4, height=3.5, dpi=300)
```

# Benjamini-Hochberg correction

```{r p_table_bh}
padj <- pdat
padj$p.value <-  p.adjust(padj$p.value, "BH")
ptbh <- pTable(padj, alpha=0.05)
str(ptbh)
```


```{r fdr_distribution_functions}
testMatrix <- function(x) {
  if(nrow(x) == 0) return(numeric(0))
  sapply(1:nrow(x), function(i) {
    t.test(x[i, ], mu=20)$p.value
  })
}

generateTestData <- function(m0, m1, n=5, M1=40) {
  H0 <- matrix(rnorm(n * m0, 20, 5), ncol=n)
  H1 <- matrix(rnorm(n * m1, M1, 5), ncol=n)
  p0 <- testMatrix(H0)
  p1 <- testMatrix(H1)
  d <- data.frame(
    Hypothesis = c(rep(0, m0), rep(1, m1)),
    p.value = c(p0, p1)
  )
  d$Hypothesis <- factor(d$Hypothesis, levels=c(1,0))
  d
}
```

```{r fdr_distribution}
set.seed(17)
nboot <- 10000
P <- mclapply(1:nboot, function(i) {
  pd <- generateTestData(970, 30)
  pd$p.value <- p.adjust(pd$p.value, method="BH")
  tab <- pTable(pd, alpha=0.05)
  tab$FDR
}, mc.cores = 4)
fdr <- unlist(P)
```

```{r plot_fdr_distribution}
fdr1 <- fdr[!is.nan(fdr)]
mean(fdr1)
fdr1[fdr1==0] <- 1e-6
dat <- data.frame(
  fdr=fdr1
)
brks <- seq(-0.01, 0.3, 0.004999)
g <- ggplot(dat) +
  geom_histogram(aes(x=fdr, y=..density..), fill=fill.colour.mid, breaks=brks) +
  scale_x_continuous() +
  scale_y_continuous(expand=c(0,0), limits=c(0, 80)) +
  geom_outline(fdr1, brks)
g

ggsave(paste0(fig, "fdr_dist.png"), plot=g, device="png", width=4, height=4.2, dpi=300)
```


```{r generate_p_data}
pnull <- generateTestData(10000, 0)
palt <- generateTestData(8000, 2000, M1=25)
pbad <- data.frame(
  p.value = c(runif(6000), 1 - runif(4000)^1.6),
  Hypothesis = factor(rep("0", 10000), levels=c("1", "0"))
)
```

```{r plot_p_dist_null_alt, fig.width=4, fig.height=3}
plotSimplePDist <- function(dat, ymax=5, plim=0.5, bin.size=0.02) {
  brks <- seq(0, 1, bin.size)
  n <- nrow(dat)
  x <- brks[-1] - bin.size
  y <- as.numeric(table(cut(dat$p.value, brks, right=TRUE))) / (bin.size * length(dat$p.value))
  y0 <- mean(y[x > plim])
  ggplot(dat) +
    theme_classic() +
    #geom_histogram(aes(x=p.value, fill=Hypothesis), breaks=brks, position="stack") +
    geom_histogram(aes(x=p.value, y=(..count..) / (n * bin.size), fill=Hypothesis), breaks=brks) +
    scale_fill_manual(values=c(fill.colour.dark, fill.colour.mid), drop=FALSE) +
    scale_y_continuous(expand=c(0,0), limits=c(0,ymax)) +
    scale_x_continuous(expand=c(0,0), limits=c(0,1), breaks=seq(0,1,0.2)) +
    labs(x="p-value", y="density") +
    geom_outline(dat$p.value, brks) +
    geom_hline(yintercept = y0) +
    theme(legend.position = "none")
}
 
palt.one <- palt
palt$Hypothesis <- factor(rep("0", 10000), levels=c("1", "0"))

g1 <- plotSimplePDist(pnull, ymax=2)
g2 <- plotSimplePDist(palt, ymax=3.5)
g3 <- plotSimplePDist(pbad, ymax=3)
g4 <- plotSimplePDist(palt.one, ymax=3.5)
g1 
g2 
g3
g4

ggsave(paste0(fig, "p_dist_null.png"), plot=g1, device="png", width=3.5, height=2.5, dpi=300)
ggsave(paste0(fig, "p_dist_alt.png"), plot=g2, device="png", width=3.5, height=2.5, dpi=300)
ggsave(paste0(fig, "p_dist_bad.png"), plot=g3, device="png", width=3.5, height=2.5, dpi=300)
ggsave(paste0(fig, "p_dist_alt_one.png"), plot=g4, device="png", width=3.5, height=2.5, dpi=300)
```


```{r pq_plot}
pqPLot <- function(d, xlim=c(0,1), ylim=NULL, x.brks=seq(0,1,0.2), y.brks=seq(0,1,0.2)) {
  d$q.value <- qvalue(d$p.value)$qv
  
  if(is.null(ylim)) {
    ylim <- c(0, 1.02*max(d[d$p.value <= xlim[2], "q.value"]))
  }
  ggplot(d, aes(x=p.value, y=q.value)) +
    theme_classic() +
    theme(plot.margin = margin(l=5, r=16, t=10)) +
    geom_line(size=0.5, colour="red") +
    scale_x_continuous(expand=c(0,0), limits=xlim, breaks=x.brks) +
    scale_y_continuous(expand=c(0,0), limits=ylim, breaks=y.brks)
}

pvalues <- read.table("http://tiny.cc/multi_FDR", header=TRUE)
pvalues$pbh <- p.adjust(pvalues$p.value, method="BH")

g0 <- pqPLot(pvalues, ylim=c(0,1)) +
  labs(x="P-value limit", y="False discovery rate") +
  geom_line(aes(x=p.value, y=pbh), colour="blue") +
  geom_hline(yintercept = qvalue(pvalues$p.value)$pi0, colour="red", linetype="dashed")
g0

g1 <- pqPLot(pvalues, ylim=c(0,1)) +
  labs(x="P-value limit", y="Point FDR")
g2 <- pqPLot(pvalues, c(0, 0.004), x.brks=seq(0,0.01, 0.002), y.brks=seq(0,0.1,0.05)) +
  labs(x=NULL, y=NULL)
g1
g2

ggsave(paste0(fig, "pq_bh.png"), plot=g0, device="png", width=3.5, height=3, dpi=300)
ggsave(paste0(fig, "pq.png"), plot=g1, device="png", width=4, height=3.5, dpi=300)
ggsave(paste0(fig, "pq_small.png"), plot=g2, device="png", width=2, height=2, dpi=300)
```