---
title: "13 What's wrong with p-values?"
output:
  html_document:
    css: tabbed_notebook.css
    fig_width: 3
    fig_height: 3
params: 
  output_dir: "../output"
---

```{r setup, echo=FALSE}
root <- "13_whats_wrong"
source("../R/setup.R")
library(boot)
library(pwr)
library(parallel)
knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  echo = FALSE,
  cache = TRUE,
  cache.path = paste0("../cache/", root),
  fig.path = paste0("../cache/", root)
)
fig <- paste0("../fig/", root, "/")
if(!dir.exists(fig)) dir.create(fig)
```

```{css echo=FALSE}
pre code, pre, code {
  white-space: pre !important;
  overflow-x: scroll !important;
  word-break: keep-all !important;
  word-wrap: initial !important;
}
```

```{r effect_palette}
efPalette <- c("lightgoldenrod3", "#009E73")
```

```{r themes}
theme_no_y <- theme(
    legend.position = "none",
    axis.line.y = element_blank(),
    axis.ticks.y = element_blank(),
    axis.text.y = element_blank(),
    axis.title.y = element_blank()
  )
```


```{r two_dist_plot_function}
plotTwoDist <- function(d1, d2, breaks, alpha=0.8, ymax=1) {
  g <- ggplot() +
    theme_classic() +
    theme_no_y +
    labs(x="Body mass (g)", y=NULL) +
    scale_y_continuous(expand=c(0,0), limits=c(0, ymax))
  g <- g +
    geom_histogram(aes(x=x), data=data.frame(x=d1), fill=efPalette[1], breaks=breaks, alpha=alpha) +
    geom_outline(d1, breaks, y.value="count", colour="grey40", alpha=alpha)+
    geom_histogram(aes(x=x), data=data.frame(x=d2), fill=efPalette[2], breaks=breaks, alpha=alpha) +
    geom_outline(d2, breaks, y.value="count", colour="grey40", alpha=alpha)
}

plotTwoP <- function(p1, p2, x.lim=c(0, 1), bins=0.01, alpha=0.8, ymax=5, x.breaks=seq(0,1,0.2)) {
  d <- data.frame(
    sample = c(rep("B", length(p1)), rep("A", length(p2))),
    value = c(p1, p2)
  )
  brks <- seq(0, 1, bins)
  
  g <- ggplot() +
    theme_classic() +
    theme(
      legend.position = "none",
      plot.margin = margin(l=10, r=10, t=6)
    ) +
    labs(x="P-value", y=NULL) +
    scale_y_continuous(expand=c(0,0), limits=c(0, ymax)) +
    scale_fill_manual(values = efPalette[2:1]) +
    scale_x_continuous(breaks=x.breaks, expand=c(0,0)) +
    coord_cartesian(xlim=x.lim)
  g <- g +
    geom_histogram(data=d, aes(x=value, y=..count../(sum(..count..) * bins), fill=sample), breaks=brks, position="stack")
  g <- g + 
    #geom_outline(p1, brks, colour="grey40", alpha=alpha) +
    geom_outline(c(p1,p2), brks, colour="grey40", alpha=alpha)
}

```



```{r plot_two_samples_97_3}
set.seed(111)
d1 <- rnorm(97000, 20, 5)
d2 <- rnorm(3000, 30, 5)
brks <- seq(0, 50, 0.5)
g <- plotTwoDist(d1, d2, ymax=4000, breaks=brks)
g 

ggsave(paste0(fig, "mice_97_3.png"), plot=g, device="png", width=3, height=3, dpi=300)
```

```{r p-values_sampling_generate}
pSampling <- function(d, n=5, nsim=10000, mu=20) {
  p <- unlist(lapply(1:nsim, function(i) {
    t.test(sample(d, n), mu = mu)$p.value
  }))
}

p1 <- pSampling(d1, nsim=97000)
p2 <- pSampling(d2, nsim=3000)
```

```{r p-values_sampling}
g1 <- plotTwoP(p1, p2, ymax=5)
g1
 
g2 <- plotTwoP(p1, p2, ymax=5, x.lim=c(0, 0.05), bins=0.001, x.breaks=seq(0, 0.05, 0.01))
g2


ggsave(paste0(fig, "mice_p_97_3.png"), plot=g1, device="png", width=3, height=3, dpi=300)
ggsave(paste0(fig, "mice_p_97_3_zoom.png"), plot=g2, device="png", width=3, height=3, dpi=300)
```








```{r plot_two_samples_50_50}
set.seed(111)
d1.5 <- rnorm(50000, 20, 5)
d2.5 <- rnorm(50000, 30, 5)
brks <- seq(0, 50, 0.5)
g <- plotTwoDist(d1.5, d2.5, ymax=2200, breaks=brks, alpha=0.6)
g

ggsave(paste0(fig, "mice_50_50.png"), plot=g, device="png", width=3, height=3, dpi=300)
```

```{r p-values_sampling_generate_50_50}
set.seed(20)
p1.5 <- pSampling(d1.5, nsim=50000)
p2.5 <- pSampling(d2.5, nsim=50000)
```

```{r p-values_sampling_50_50}
g1 <- plotTwoP(p1.5, p2.5, ymax=60, x.lim=c(0, 0.05), bins=0.001, x.breaks=seq(0, 0.05, 0.01))
g1
 
g2 <- plotTwoP(p1.5, p2.5, ymax=3, x.lim=c(0.04, 0.06), bins=0.001, x.breaks=seq(0, 0.1, 0.005))
g2

ggsave(paste0(fig, "mice_p_50_50.png"), plot=g1, device="png", width=3, height=3, dpi=300)
ggsave(paste0(fig, "mice_p_50_50_zoom.png"), plot=g2, device="png", width=3, height=3, dpi=300)
```


```{r p_reliability_generate}
set.seed(991)
p.3 <- pSampling(rnorm(10000, 25, 5), n = 3, nsim=100000)
p.10 <- pSampling(rnorm(10000, 25, 5), n = 10, nsim=100000)
```

```{r plot_p_reliability}
g1 <- plotOneDist(p.3, "p-value", "", limits=c(0,1), fill=efPalette[2], with.outline = TRUE) +
  scale_x_continuous(expand=c(0,0), breaks=seq(0,1,0.2), labels=seq(0,1,0.2))
g2 <- plotOneDist(p.10, "p-value", "", limits=c(0,1), fill=efPalette[2], with.outline = TRUE) +
  scale_x_continuous(expand=c(0,0), breaks=seq(0,1,0.2), labels=seq(0,1,0.2))


g1
g2

ggsave(paste0(fig, "mice_p_full_3.png"), plot=g1, device="png", width=3, height=3, dpi=300)
ggsave(paste0(fig, "mice_p_full_10.png"), plot=g2, device="png", width=3, height=3, dpi=300)

```


```{r effect_size_generate}
set.seed(3736)
nsim <- 100000
mu <- 20
n <- 3

pop <- rnorm(10000, 25, 5)
L <- lapply(1:nsim, function(i) {
  x <- sample(pop, n)
  M <- mean(x)
  p <- t.test(x, mu = mu)$p.value
  data.frame(M=M, p=p)
})
eff <- do.call(rbind, L)
```

```{r plot_effect_size}
eff$sig <- eff$p < 0.05
mean(eff[eff$sig, "M"])

brks <- seq(10, 40, 0.2)
g1 <- ggplot(eff) +
  theme_classic() +
  theme_no_y +
  geom_histogram(aes(x=M, fill=sig), breaks=brks) +
  scale_x_continuous(expand=c(0,0)) +
  scale_fill_manual(values=efPalette) +
  geom_outline(eff$M, brks, y.value = "count", colour="grey30", size=0.3) +
  labs(x="Sample mean (g)") +
  geom_vline(xintercept = 20) +
  geom_vline(xintercept = 25, linetype="dotted")

  maxh <- max(ggplot_build(g1)$data[[1]]$y)  # max count in histogram
  g1 <- g1 + scale_y_continuous(expand=c(0,0), limits=c(0, maxh*1.03))


g2 <- plotDistributionCut(eff$p, cut=0.05, brks=seq(0,1,0.01), fill=efPalette[2], fill.cut=efPalette[1], outline.colour="grey30", xlab="P-value", x.brks = seq(0, 1, 0.2)) +
  theme_no_y
g1
g2

ggsave(paste0(fig, "effect_size_M.png"), plot=g1, device="png", width=3, height=3, dpi=300)
ggsave(paste0(fig, "effect_size_p.png"), plot=g2, device="png", width=3, height=3, dpi=300)

```


```{r large_samples}
#set.seed(44)
#s1 <- rnorm(775, 0.45, 0.2)
#s2 <- rnorm(392, 0.484, 0.2)

X <- read.table("../data/all_update.txt", header=FALSE, sep="\t")
X <- setNames(X[, c(11, 30)], c("distance", "strain"))

d <- X[X$strain %in% c("70.6kb", "71kb"), ]
d$distance <- d$distance / 1000

m <- d %>% group_by(strain) %>% summarise(M = mean(distance), SE = sd(distance) / sqrt(n()))

t.test(distance ~ strain, data=d)

g1 <- ggplot(m) +
  theme_classic() +
  geom_errorbar(aes(x=strain, ymin=M-SE, ymax=M+SE), width=0.1) +
  geom_col(aes(x=strain, y=M), fill="black", width=0.5) +
  scale_y_continuous(expand=c(0,0), limits=c(0, max(m$M + m$SE)*1.03)) +
  labs(x=NULL, y = ~ "Distance ("*mu*m*")")
g1

g2 <- ggplot() +
    theme_classic() +
    theme(legend.position = "none") +
    scale_colour_manual(values=cbPalette) +
    geom_beeswarm(data=d, aes(x=strain, y=distance), cex=1, size=0.15, priority = "density") +
    labs(x=NULL, y = ~ "Distance ("*mu*m*")")

    g2 <- g2 + geom_boxplot(data=m, aes(x=strain, middle=M, ymin=M, lower=M, upper=M, ymax=M), stat="identity", width=0.7, lwd=0.6, fatten=0, colour="darkgoldenrod3")

g2
ggsave(paste0(fig, "large_sample_shitplot.png"), plot=g1, device="png", width=2, height=3, dpi=300)
ggsave(paste0(fig, "large_sample.png"), plot=g2, device="png", width=2.5, height=3, dpi=300)

```
