---
title: "14 Linear models"
output:
  html_document:
    css: tabbed_notebook.css
    fig_width: 3
    fig_height: 3
params: 
  output_dir: "../output"
---

```{r setup, echo=FALSE}
root <- "14_linear_models"
source("../R/setup.R")
library(car)
knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  echo = FALSE,
  cache = TRUE,
  cache.path = paste0("../cache/", root),
  fig.path = paste0("../cache/", root)
)
fig <- paste0("../fig/", root, "/")
if(!dir.exists(fig)) dir.create(fig)
```

```{css echo=FALSE}
pre code, pre, code {
  white-space: pre !important;
  overflow-x: scroll !important;
  word-break: keep-all !important;
  word-wrap: initial !important;
}
```



```{r generate_simple_mice, echo=FALSE}
set.seed(125)
f <- function(kcal) {
  f <- 20 + 0.5 * kcal + rnorm(length(kcal), 0, 1)
}

kcal <- runif(10, 2, 10)
ms <- data.frame(
  kcal = round(kcal, 1),
  mass = round(f(kcal),1)
)
```

```{r simple_mouse_table, echo=FALSE}
kable(ms, format="html", digits=1, row.names=TRUE) %>% kable_styling("condensed", full_width = FALSE, position="left")
```



```{r simple_model_fit, echo=FALSE}
ms.fit <- lm(mass ~ kcal, data=ms)
summary(ms.fit)$coefficients

ms$model = predict(ms.fit)
```



```{r simple_model_plot, fig.width=3, fig.height=2.5}
cf <- coef(ms.fit)
gg1 <- ggplot(ms, aes(x=kcal, y=mass)) +
  theme_classic() +
  labs(x="Daily calorific input (kcal)", y="Body mass (g)")

g1 <- gg1 + geom_point() + geom_abline(intercept=cf[1], slope=cf[2], colour="red") 
g2 <- gg1 + geom_segment(aes(xend=kcal, yend=model), colour="grey60") +
  geom_point() + geom_abline(intercept=cf[1], slope=cf[2], colour="red") 

g1
g2

ggsave(file.path(fig, "simple_linear.png"), g1, "png", width=3, height=3)
ggsave(file.path(fig, "simple_linear_residuals.png"), g2, "png", width=3, height=3)
```


```{r dat5, echo=FALSE}
set.seed(1)
n1 <- 2
n2 <- 3
row <- c(rnorm(n1, 20, 5), rnorm(n2, 30, 5)) %>% round(1)
samples <- c(rep('norm', n1), rep('hifat', n2))
md <- tibble(mass=row, diet=samples %>% as_factor() %>% fct_relevel("norm"))
```


```{r show_dat5, echo=FALSE}
kable(md, format="html", digits=1, row.names=TRUE) %>% kable_styling("condensed", full_width = FALSE, position="left")
```

```{r design_diet}
model.matrix(mass ~ diet, data=md)
model.matrix(mass ~ 0 + diet, data=md)
```



```{r fit_dat5}
fit = lm(mass ~ diet, data = md)
summary(fit)$coefficients

fit0 = lm(mass ~ 0 + diet, data = md)
summary(fit0)$coefficients
```


```{r plot_fit_coefficients_function, echo=FALSE}
plotFitCoefficients <- function(dat, cf, nudge=NULL, text.size=14, with.baseline=TRUE) {
  cf.names <- names(cf)
  n <- length(cf)
  if(cf.names[1] == "(Intercept)") {
    arr <- data.frame(
      x = 1:n,
      lo = c(0, rep(cf[1], n - 1)),
      up = c(cf[1], cf[2:n] + cf[1])
    )
  } else {
    arr <- data.frame(
      x = 1:n,
      lo = c(rep(0, n)),
      up = cf
    )
  }
  dat$x <- as.numeric(as.factor(dat$group))
  
  gdat <- dat %>% group_by(group) %>% summarise(M = mean(value)) %>% as.data.frame
  gdat$cf.name <- cf.names
  gdat <- cbind(gdat, arr)
  gdat$text.y <- (gdat$lo + gdat$up) / 2
  if(!is.null(nudge)) gdat$text.y <- gdat$text.y + nudge
  
  dw <- 0.1
  g <- ggplot(dat, aes(x=x, y=value)) +
    theme_classic() +
    theme(text = element_text(size=text.size)) +
    geom_point(size=2, shape=21, fill="grey70") +
    scale_x_continuous(breaks=1:n, labels=gdat$group, limits=c(0.7, n+0.3)) +
    scale_y_continuous(expand=c(0,0), limits=c(0, 1.05*max(dat$value))) +
    theme(legend.position = "none") +
    scale_colour_manual(values=c(cbPalette, "black")) +
    geom_segment(data=gdat, aes(x=x-dw, xend=x+dw, y=M, yend=M), size=1) +
    geom_segment(data=gdat, aes(x=x, xend=x, y=lo, yend=up, colour=as.factor(x))) +
    geom_segment(data=gdat, aes(x=x-dw, xend=x+dw, y=up, yend=up, colour=as.factor(x))) +
    geom_text(data=gdat, aes(x=x+0.1, y=text.y, label=cf.name, colour=as.factor(x)), angle=90) +
    labs(x=NULL, y="Body mass (g)")
  if(with.baseline) g <- g + geom_hline(yintercept = cf[1], colour="grey50", linetype="dotted")
  g
}

plotCoefficients <- function(fit, nudge=0.7) {
  fit %>% 
    broom::tidy() %>% 
  ggplot(aes(x=term, y=estimate, ymin=estimate-std.error, ymax=estimate+std.error)) +
    theme_classic() +
    geom_errorbar(width=0.3) +
    geom_point() +
    geom_text(aes(y=estimate+std.error, label=signif(p.value,2)), nudge_y = nudge, size=3) +
    labs(x=NULL, y="Estimate") +
    scale_y_continuous(expand=expansion(mult=c(0, 0.05)), limits=c(0, NA))
}
```

```{r plot_g5, fig.width=3, fig.height=3}
md$dietnum <- as.numeric(md$diet == "hifat")
cf <- coef(fit)
m <- md %>% 
  group_by(dietnum) %>% 
  summarise(M = mean(mass))


g5 <- ggplot(md, aes(x=dietnum, y=mass, fill=diet)) +
  theme_classic() +
  theme(text=element_text(size=14)) +
  geom_errorbar(data=m, aes(y=M, ymin=M, ymax=M, width=0.4, fill=NA)) +
  geom_point(size=3, shape=21) +
  theme(legend.position = "none") +
  scale_fill_manual(values=cbPalette) +
  scale_x_continuous(breaks=c(0,1), labels=c("norm", "hifat"), limits=c(-0.3, 1.3)) +
  labs(x="", y="Body mass (g)")
g5

ggsave(file.path(fig, "mice_diet.png"), g5, "png", width=3, height=3)

g5s <- g5 +
  geom_abline(slope = cf[2], intercept = cf[1], colour="red") +
  scale_x_continuous(breaks=c(0,1), labels=c(0, 1), limits=c(-0.3, 1.3))
g5s
ggsave(file.path(fig, "mice_diet_linear.png"), g5s, "png", width=3, height=3)

g50 <- g5 + scale_y_continuous(expand=expansion(mult=c(0,0.05)), limits=c(0,NA))
g50
ggsave(file.path(fig, "mice_diet_0.png"), g50, "png", width=3, height=3)

```

```{r mouse_coef, fig.width=3, fig.height=3}
cf <- coef(fit)
d <- md %>% mutate(group = diet, value=mass) 
g <- plotFitCoefficients(d, cf)
g

ggsave(file.path(fig, "mice_diet_coef.png"), g, "png", width=3, height=3)

cf0 <- coef(fit0)
g <- plotFitCoefficients(d, cf0, with.baseline = FALSE)
g

ggsave(file.path(fig, "mice_diet_coef0.png"), g, "png", width=3, height=3)

```


```{r mouse_pval, fig.width=3, fig.height=3}
g <- plotCoefficients(fit, nudge=0.8)
g

ggsave(file.path(fig, "mice_diet_pval.png"), g, "png", width=2, height=2.5)


g <- plotCoefficients(fit0, nudge=1.2)
g

ggsave(file.path(fig, "mice_diet_pval0.png"), g, "png", width=2, height=2.5) 

```

```{r ttest_dat5}
t.test(mass ~ diet, data = md, var.equal=TRUE)
```


```{r dat12, echo=FALSE}
set.seed(1)
n1 <- 6
n2 <- 6
row <- c(rnorm(n1, 20, 5), rnorm(n2, 30, 5)) %>% round(1)
samples <- c(rep('norm', n1), rep('hifat', n2))
sex <- c('f', 'f', 'f', 'm', 'm', 'm', 'f', 'f', 'f', 'm', 'm', 'm')
mds <- tibble(mass=row, diet=factor(samples), sex=factor(sex)) %>% 
  mutate(diet = fct_relevel(diet, "norm"), sex = fct_relevel(sex, "f"))

kable(mds, format="html", digits=1, row.names=TRUE) %>% kable_styling("condensed", full_width = FALSE, position="left")
```


```{r dat12_plot, fig.width=5, fig.height=3.5, echo=FALSE}
mds$group <- paste0(mds$diet, "_", mds$sex)
mds$group <- factor(mds$group, levels=c("norm_f", "hifat_f", "norm_m", "hifat_m"))

m <- mds %>% group_by(group) %>% summarise(M = mean(mass))

g <- ggplot(mds) +
  theme_classic() +
  theme(text=element_text(size=14)) +
  geom_errorbar(data=m, aes(x=group, y=M, ymin=M, ymax=M, width=0.4)) +
  geom_point(aes(x=group, y=mass, colour=diet, shape=sex), size=2) +
  scale_colour_manual(values=cbPalette) +
  labs(x=NULL, y="Body mass (g)")
g

ggsave(file.path(fig, "mice_diet_sex.png"), g, "png", width=4.5, height=3)
```

```{r design_mouse_sex}
model.matrix(mass ~ diet + sex, data=mds)
```

```{r fit_sex}
fmds <- lm(mass ~ diet + sex, data = mds)
summary(fmds)$coefficients
```



```{r fit_coefficients2, fig.width=5, fig.height=3.6, echo=FALSE}
dat <- data.frame(
  group = paste0(mds$diet, "_", mds$sex),
  value = mds$mass
)
dat$group <- factor(dat$group, levels=c("norm_f", "hifat_f", "norm_m", "hifat_m"))
cf <- coef(fmds)
cf <- c(cf, cf[2] + cf[3])
names(cf)[4] <- "dietfat + sexm"
g <- plotFitCoefficients(dat, cf, nudge=c(0, 0, -2, -1)) 
g

ggsave(file.path(fig, "mice_diet_sex_coef.png"), g, "png", width=4, height=3)

```



```{r fit2_dat12}
f <- lm(mass ~ diet + sex + diet:sex, data = mds)
summary(f)$coefficients
```

```{r anova2_plot_function}
plotAnova2 <- function(mice, ylim=c(0,40), text.size=10) {
  grand.mean <- mean(mice$mass)
  mice.gr <- mice %>% group_by(diet, sex) %>% summarise(M = mean(mass))

  g1 <- ggplot(mice, aes(x=1, y=mass)) +
    theme_classic() +
    facet_grid(sex ~ diet, switch="both") +
    geom_hline(yintercept = grand.mean, linetype = "dotted", size=0.3) +
    #geom_boxplot(aes(fill=diet), alpha=0.5, outlier.shape = NA, width=0.7) +
    scale_fill_manual(values=cbPalette) +
    geom_beeswarm(aes(fill=diet), cex=6.5, size=1.5, shape=21) +
    labs(x="", y="") +
    ylim(ylim) +
    xlim(0, 2) +
    theme(
      legend.position = "none",
      strip.background = element_blank(),
      strip.text = element_text(size=text.size),
      panel.spacing = unit(0, "cm"),
      panel.border = element_rect(fill=NA),
      axis.ticks = element_blank(),
      axis.text = element_blank(),
      axis.line = element_blank()
    )
  
  g2 <- ggplot(mice.gr, aes(x=diet, y=M, group=sex, colour=sex)) +
    theme_classic() +
    geom_line(aes(group=sex)) +
    geom_point(aes(fill=sex), size=2, shape=22) +
    labs(x="", y="") +
    ylim(ylim) +
    geom_hline(yintercept = grand.mean, linetype = "dotted", size=0.3) +
    scale_colour_manual(values=c("grey60", "black")) +
    scale_fill_manual(values=c("white", "black")) +
    scale_x_discrete(position = "top") +
    theme(
      panel.border = element_rect(colour="black", linetype="solid", fill=NA),
      legend.position = "none",
      axis.ticks = element_blank(),
      axis.text.y = element_blank(),
      panel.spacing = unit(0, "cm"),
      axis.line = element_blank(),
      axis.text = element_text(size=text.size),
      plot.margin = unit(c(-0.5,0,0,0),"cm")
    )
  
  g3 <- ggplot(mice.gr, aes(x=sex, y=M, group=diet, colour=diet)) +
    theme_classic() +
    geom_line(aes(group=diet)) +
    geom_point(aes(colour=diet, fill=diet), size=2, shape=22) +
    labs(x="", y="") +
    ylim(ylim) +
    geom_hline(yintercept = grand.mean, linetype = "dotted", size=0.3) +
    scale_colour_manual(values=cbPalette) +
    scale_fill_manual(values=cbPalette) +
    scale_x_discrete(position = "bottom") +
    theme(
      panel.border = element_rect(colour="black", linetype="solid", fill=NA),
      legend.position = "none",
      axis.ticks = element_blank(),
      axis.text.y = element_blank(),
      panel.spacing = unit(0, "cm"),
      axis.line = element_blank(),
      axis.text = element_text(size=text.size),
      plot.margin = unit(c(0,0,0.6,0),"cm")
    )
  
  left_col <- g1
  right_col <- plot_grid(g2, g3, ncol=1, rel_heights = c(1, 1.33))
  
  plot_grid(left_col, right_col, ncol=2, rel_widths = c(1, 0.6))
}
```

```{r fig_anota, fig.width=6, fig.height=3}
g <- mds %>%
  mutate(sex = recode_factor(sex, "m"="male", "f"="female")) %>% 
  plotAnova2()
g

ggsave(file.path(fig, "anova.png"), g, "png", width=5, height=3.5)
```


```{r fit_coefficients2_inter, fig.width=5, fig.height=3.5, echo=FALSE}
dat <- data.frame(
  group = paste0(mds$diet, "_", mds$sex),
  value = mds$mass
)
dat$group <- factor(dat$group, levels=c("norm_f", "hifat_f", "norm_m", "hifat_m"))
cf <- coef(f)
cf[4] <- cf[2] + cf[3] + cf[4]
names(cf)[4] <- "dietfat + sexm + diethifat:sexm"
g <- plotFitCoefficients(dat, cf, nudge=c(0, 0, -1, -7)) 

ggsave(file.path(fig, "mice_diet_sex_inter_coef.png"), g, "png", width=4, height=3)
```



```{r car_data}
sal <- as_tibble(Salaries) %>% 
  mutate(rank = fct_relevel(rank, "AsstProf"))
myKable(sal[1:10,])
```

```{r car_plot, fig.width=8, fig.height=5}
plotSal <- function(sal, what) {
  sal <- mutate(sal, x = !!sym(what))
  g <- ggplot(sal, aes(x=x, y=salary)) +
    theme_bw() +
    theme(panel.grid = element_blank()) +
    labs(x=what, y="salary")
  if(is.factor(sal$x)) {
    g <- g + geom_boxplot(outlier.shape = NA) + geom_beeswarm(size=0.6, colour="grey50")
  } else {
    g <- g + geom_point(size=0.6, colour="grey50")
  }
  g
}

snames <- colnames(sal %>% select(-salary))
g <- map(snames, ~plotSal(sal, .x)) %>% 
  plot_grid(plotlist = .)
g

ggsave(file.path(fig, "salaries.png"), g, "png", width=8, height=5)

g1 <- ggplot(sal, aes(x=yrs.since.phd, y=yrs.service)) +
  theme_bw() +
  theme(panel.grid = element_blank()) +
  geom_point(size=0.6)
g1

ggsave(file.path(fig, "salaries_years.png"), g1, "png", width=3, height=2.5)
```


```{r sal_matrix}
model.matrix(salary ~ rank + discipline + yrs.since.phd + sex, data=sal)
```


```{r sal_sex}
f1 <- lm(salary ~ sex, data=sal)
summary(f1)

f2 <- lm(salary ~ rank + discipline + yrs.since.phd + sex, data=sal)
summary(f2)

f3 <- lm(salary ~ rank + discipline + yrs.since.phd + yrs.service + sex, data=sal)
summary(f3)

f4 <- lm(salary ~ rank + discipline, data=sal)
summary(f4)
```

```{r sal_cor}
vif(f3)
vif(f2)
```

```{r sal_train, fig.width=4, fig.height=4}
set.seed(2021)
itest <- sample(1:nrow(sal), 40)
itrain <- setdiff(1:nrow(sal), itest)

sal_train <- sal[itrain, ]
sal_test <- sal[itest, ]

lm.train <- lm(salary ~ rank + discipline, data=sal_train)
sal_test <- bind_cols(sal_test, predict(lm.train, sal_test, interval="confidence") %>% as_tibble())

mn <- min(c(sal_test$salary, sal_test$fit))
mx <- max(c(sal_test$salary, sal_test$fit))
g <- sal_test %>% 
  ggplot(aes(x=salary, y=fit, ymin=lwr, ymax=upr)) +
  theme_bw() +
  theme(panel.grid = element_blank()) +
  geom_errorbar(width=0, colour="grey70") +
  geom_point() +
  geom_abline(slope=1, intercept = 0, colour="red") +
  labs(x="Salary", y="Predicion") +
  scale_x_continuous(labels=scales::comma, limits=c(mn, mx)) +
  scale_y_continuous(labels=scales::comma, limits=c(mn, mx))
g

ggsave(file.path(fig, "salaries_prediction.png"), g, "png", width=4, height=4)
```


```{r r2}
plot_r2 <- function(d) {
  M <- mean(d$y)
  mod <- lm(y ~ x, data=d)
  cf <- coef(mod)
  R2 <- summary(mod)$r.squared
  
  d %>%
    mutate(pred = predict(mod, d)) %>% 
  ggplot(aes(x=x, y=y)) +
    theme_bw() +
    theme(panel.grid = element_blank()) +
    geom_segment(aes(xend=x, yend=pred), colour="red") +
    geom_segment(aes(xend=x, yend=M), colour="orange", linetype="dashed") +
    geom_point() +
    geom_abline(slope=cf[2], intercept = cf[1], colour="red") +
    geom_hline(yintercept = M, colour="orange", linetype="dashed") +
    labs(title=sprintf("R2 = %4.2f", R2))
}

set.seed(61234)
x <- 1:10
d1 <- tibble(x = x, y = 1*x + rnorm(10, 5))
g1 <- plot_r2(d1)
g1

set.seed(4336)
d2 <- tibble(x = x, y = 0 + rnorm(10, 5))
g2 <- plot_r2(d2)
g2

ggsave(file.path(fig, "r2_large.png"), g1, "png", width=4, height=4)
ggsave(file.path(fig, "r2_small.png"), g2, "png", width=4, height=4)
```


```{r female_ratio}
fs <- Salaries %>% 
  group_by(rank) %>% 
  summarise(n_female = sum(sex == "Female"), n_male = sum(sex == "Male"), n = n()) %>% 
  nest(data = c(n_female, n)) %>% 
  mutate(
    test = map(data, ~prop.test(.x$n_female, .x$n)),
    tidied = map(test, broom::tidy)
  ) %>% 
  unnest(tidied)

g <- ggplot(fs, aes(x=rank, y=estimate, ymin=conf.low, ymax=conf.high)) +
  theme_bw() +
  theme(panel.grid = element_blank()) +
  geom_errorbar(width=0.3, colour="grey") +
  geom_point() +
  labs(x="Rank", y="Female propotion") +
  scale_y_continuous(expand=expansion(mult = c(0, 0.05)), limits=c(0, NA))

ggsave(file.path(fig, "female_proportion.png"), g, "png", width=4, height=4)

```
