---
title: "Lecture 7"
output:
  html_document:
    css: tabbed_notebook.css
params: 
  output_dir: "../output"
---

```{r setup, echo=FALSE}
source("../R/setup.R")
knitr::opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  echo = FALSE,
  cache = TRUE,
  cache.path = "../cache/lecture7/",
  fig.path = "../cache/lecture7/"
)
fig <- "../fig/L7/"
if(!dir.exists(fig)) dir.create(fig)
#library(kolmim)
library(boot)
library(pwr)
```

```{css echo=FALSE}
pre code, pre, code {
  white-space: pre !important;
  overflow-x: scroll !important;
  word-break: keep-all !important;
  word-wrap: initial !important;
}
```

```{r countries}
countries <- c("English", "Scottish", "Welsh", "N.Irish")
```


```{r plot_mice_box_function}
plotMiceBox <- function(mice, seed=111, limits=NULL) {
  set.seed(seed)
  g <- ggplot(mice, aes(x=Country, y=Mass)) +
    theme_classic() +
    theme(legend.position = "none") +
    geom_boxplot(aes(fill=Country), alpha=0.5, outlier.shape = NA) +
    scale_fill_manual(values=british.palette) +
    geom_jitter(width=0.15, height=0) +
    labs(x="", y="Body mass (g)")
  if(!is.null(limits)) g <- g + ylim(limits)
  g
}
```


```{r generate_cohens_d}
CohensD <- function(x1, x2) {
  n1 <- length(x1)
  n2 <- length(x2)
  M1 <- mean(x1)
  M2 <- mean(x2)
  S1 <- sd(x1)
  S2 <- sd(x2)
  S12 <- sqrt(((n1 - 1) * S1^2 + (n2 - 1) * S2^2) / (n1 + n2 - 2))
  d <- abs(M2 - M1) / S12
}

generateCohensD <- function(M, S, n, d, eps=1e-4, epsM=0.1, epsS=0.1, restrict.M2=FALSE) {
  M1 <- M
  M2 <- M1 + d * S
  repeat {
    repeat {
      x1 <- rnorm(n, M1, S)
      if(abs(mean(x1) - M1) < epsM && abs(sd(x1) - S) < epsS) break
    }
    if(restrict.M2) {
      repeat {
        x2 <- rnorm(n, M2, S)
        if(abs(mean(x2) - M2) < epsM) break
      }
    } else {
      x2 <- rnorm(n, M2, S)
    }
    dr <- CohensD(x1, x2)
    if(abs(d - dr) < eps) break
  }
  data.frame(
    Country = c(rep("English", n), rep("Scottish", n)),
    Mass = c(x1, x2)
  )
}


generateFoldChange <- function(M, S, n, FC, epsM=0.1, epsS=0.1) {
  M1 <- M
  M2 <- M1 * FC
  repeat {
      x1 <- rnorm(n, M1, S)
      if(abs(mean(x1) - M1) < epsM) break
  }
  repeat {
      x2 <- rnorm(n, M2, S)
      if(abs(mean(x2) - M2) < epsM) break
  }
  data.frame(
    Country = c(rep("English", n), rep("Scottish", n)),
    Mass = c(x1, x2)
  )
}
```

```{r cohens_d_example, fig.width=2.5, fig.height=3}
dat <- generateCohensD(20, 5, 12, 1.1)
g <- plotMiceBox(dat)
g

ggsave(paste0(fig, "cohens_d_example.png"), plot=g, device="png", width=2.5, height=3.5, dpi=300)
```

```{r cohens_d_size}
cohens.sizes <- data.frame(
  size = c("Very small", "Small", "Medium", "Large", "Very large", "Huge"),
  d = c(0.01, 0.2, 0.5, 0.8, 1.2, 2),
  stringsAsFactors = FALSE
)
rownames(cohens.sizes) <- cohens.sizes$size

n <- 10
M <- 20
S <- 5
P <- lapply(cohens.sizes$size, function(size) {
  d <- cohens.sizes[size, "d"]
  dat <- generateCohensD(M, S, n, d)
  dat$Size <- size
  dat
})
coh <- do.call(rbind, P)
coh$Size <- factor(coh$Size, levels=cohens.sizes$size)
```

```{r cohens_d_size_plot, fig.width=8, fig.height=3}
g <- plotMiceBox(coh) +
  facet_grid(. ~ Size) +
  labs(y="") +
  ylim(min(coh$Mass), max(coh$Mass)) +
      theme(
      legend.position = "none",
      strip.background = element_blank(),
      strip.text = element_text(size=12),
      panel.spacing = unit(0, "cm"),
      panel.border = element_rect(fill=NA),
      axis.ticks = element_blank(),
      axis.text = element_blank(),
      axis.line = element_blank()
    )
 
g
ggsave(paste0(fig, "cohens_d_size.png"), plot=g, device="png", width=8, height=4, dpi=300)
```

```{r cohens_fold_change, fig.width=5, fig.height=3}
n <- 10
M <- 20

foldChangeFig <- function(S, FC=2) {
  fc <- generateFoldChange(M, S, n, FC)
  d <- CohensD(subset(fc, Country=="English")$Mass, subset(fc, Country=="Scottish")$Mass)
  print(d )
  plotMiceBox(fc) + ylim(0,50)
}

set.seed(23)
g1 <- foldChangeFig(15)
g2 <- foldChangeFig(5)
g3 <- foldChangeFig(1)
g <- plot_grid(g1, g2, g3, ncol=3)
g

ggsave(paste0(fig, "cohens_d_fold_change.png"), plot=g, device="png", width=5, height=3, dpi=300)
```


```{r cohens_sample_size, fig.width=5, fig.height=3}
S <- 5
M <- 20

sampleSizeFig <- function(n, d) {
  dat <- generateCohensD(M, S, n, d)
  t <- abs(as.numeric(t.test(Mass ~ Country, data=dat)$statistic))
  print(t)
  plotMiceBox(dat) + ylim(0,50)
}

set.seed(77)
g1 <- sampleSizeFig(5, 0.8)
g2 <- sampleSizeFig(20, 0.8)
g3 <- sampleSizeFig(50, 0.8)
g <- plot_grid(g1, g2, g3, ncol=3)
g

ggsave(paste0(fig, "cohens_d_sample_size.png"), plot=g, device="png", width=5, height=3, dpi=300)
```

```{r generate_null_alternative}
generatet <- function(M1=20, M2=20, S=5, n=5, nsim=100000) {
  P <- lapply(1:nsim, function(i) {
    x1 <- rnorm(n, M1, S)
    x2 <- rnorm(n, M2, S)
    test <- t.test(x1, x2, var.equal=TRUE)
    t <- test$statistic[['t']]
  })
  unlist(P)
}

n <- 5
H0 <- generatet(20, 20, n=n)
H1 <- generatet(30, 20, n=n)
```

```{r plot_H0_H1, fig.width=3, fig.height=2}
t0 <- qt(0.975, 2 * n - 2)

g1 <- plotDistributionCut(H0, cut=NULL, brks=seq(-5, 10, 0.1), fill=fill.colour)
g1.cut <- plotDistributionCut(H0, cut=t0, side="both", brks=seq(-5, 10, 0.1), fill=fill.colour) +
  geom_vline(xintercept = -t0) + geom_vline(xintercept = t0)
g1.cut
 
g2 <- plotDistributionCut(H1, cut=NULL, brks=seq(-5, 10, 0.1), fill=fill.colour)
g2.cut <- plotDistributionCut(H1, cut=t0, side="lower", brks=seq(-5, 10, 0.1), fill=fill.colour) +
  geom_vline(xintercept = -t0) + geom_vline(xintercept = t0)
g2.cut
length(which(H1 > t0)) / 100000

ggsave(paste0(fig, "t_h0.png"), plot=g1, device="png", width=3.5, height=1.9, dpi=300)
ggsave(paste0(fig, "t_h1.png"), plot=g2, device="png", width=3.5, height=1.9, dpi=300)
ggsave(paste0(fig, "t_h0_cut.png"), plot=g1.cut, device="png", width=3.5, height=1.9, dpi=300)
ggsave(paste0(fig, "t_h1_cut.png"), plot=g2.cut, device="png", width=3.5, height=1.9, dpi=300)
```



```{r generate_null_alternative_anova}
generatea <- function(M1=20, M2=20, M3=20, M4=20, S=5, n=5, nsim=100000) {
  P <- lapply(1:nsim, function(i) {
    x1 <- rnorm(n, M1, S)
    x2 <- rnorm(n, M2, S)
    x3 <- rnorm(n, M3, S)
    x4 <- rnorm(n, M4, S)
    dat <- data.frame(
      value = c(x1, x2, x3, x4),
      group = c(rep("1", n), rep("2", n), rep("3", n), rep("4", n))
    )
    test <- aov(value ~ group, data=dat)
    F <- summary(test)[[1]]$F[1] 
  })
  unlist(P)
}

n <- 5
H0 <- generatea(20, 20, 20, 20, n=n)
H1 <- generatea(20, 20, 25, 25, n=n)
```

```{r plot_H0_H1_anova, fig.width=3, fig.height=2}
f0 <- 2.8

g1.cut <- plotDistributionCut(H0, cut=f0, side="upper", brks=seq(0, 15, 0.1), fill=fill.colour) +
  scale_x_continuous(expand=c(0,0), limits=c(0,15)) +
  geom_vline(xintercept = f0)
g1.cut
 
g2.cut <- plotDistributionCut(H1, cut=f0, side="lower", brks=seq(0, 15, 0.1), fill=fill.colour) +
  scale_x_continuous(expand=c(0,0), limits=c(0,15)) +
  geom_vline(xintercept = f0)
g2.cut
length(which(H1 > f0)) / 100000

ggsave(paste0(fig, "anova_h0_cut.png"), plot=g1.cut, device="png", width=3.5, height=1.9, dpi=300)
ggsave(paste0(fig, "anova_h1_cut.png"), plot=g2.cut, device="png", width=3.5, height=1.9, dpi=300)
```





```{r plot_two_t_function}
# non-centrality parameter for populations
ncp <- function(dM, S, n) {
  d <- dM / S   # effect size for populations
  ncp <- d * sqrt(n / 2)
}


plotTwoT <- function(M1, M2, S=5, n=5) {
  tcut <- qt(0.975, 2 * n - 2)
  np <- ncp(M2 - M1, S, n)
  x <- seq(-5, 10, 0.01)
  t0 <- dt(x, 2*n - 2)
  t1 <- dt(x, 2*n-2, ncp=np)
  dat <- data.frame(
    x = x,
    t0 = t0,
    t1 = t1
  )
  
  x.cut <- seq(tcut, 10, 0.01)
  t1.cut <- dt(x.cut, 2*n-2, ncp=np)
  dat.cut <- data.frame(
    x = c(tcut, x.cut, 10),
    t1 = c(0, t1.cut, 0)
  )
  
  mx <- max(dat$t0) * 1.02
  
  g <- ggplot() +
    theme_classic() +
    geom_polygon(data=dat.cut, aes(x, t1), fill=fill.colour.mid) +
    geom_line(data=dat, aes(x, t1)) +
    geom_line(data=dat, aes(x, t0)) +
    geom_vline(xintercept = tcut) +
    geom_vline(xintercept = -tcut) +
    scale_y_continuous(expand=c(0,0), limits=c(0, mx)) +
    theme(
      axis.line.y = element_blank(),
      axis.ticks.y = element_blank(),
      axis.title = element_blank(),
      axis.text.y = element_blank()
    ) +
    labs(x="")
  
  g
}


powerTTest <- function(dM, S, n) {
  P <- lapply(dM, function(dm) {
    np <- ncp(dm, S, n)
    tcut <- qt(0.975, 2 * n - 2)
    p <- 1 - pt(tcut, 2*n - 2, np)
    d <- dm / S
    data.frame(
      d = d,
      power = p
    )
  })
  do.call(rbind, P)
}
```


```{r power_t_dist, fig.width=4, fig.height=5}
M <- c(22, 24, 26, 28, 30) 
 
pow <- powerTTest(M - 20, S=5, n=5)
myKable(pow)

P <- lapply(M, function(m) {
  plotTwoT(20, m, S=5, n=5)
})

g <- plot_grid(P[[1]], P[[2]], P[[3]], P[[4]], P[[5]], ncol=1)
g

ggsave(paste0(fig, "t_power_5dist.png"), plot=g, device="png", width=4, height=5, dpi=300)
```


```{r t_power_curve_5, fig.width=3, fig.height=3}
tPowerCurve <- function(n=seq(2,10,1), delta=seq(-10, 10, 0.1)) {
  D <- data.frame()
  for(i in n) {
    for(s in delta) {
      D <- rbind(D, data.frame(
        n = i,
        delta = s,
        power = power.t.test(n=i, delta=s)$power
      ))
    }
  }
  D
}


sPowerCurve <- function(n=seq(2,50,1), power=c(0.6, 0.8, 0.95)) {
  D <- data.frame()
  for(k in n) {
    for(p in power) {
      D <- rbind(D, data.frame(
        n = k,
        power = p,
        delta = power.t.test(n=k, power=p, sd=1, alternative = "two.sided")$delta
      ))
    }
  }
  D
}

pow <- tPowerCurve(n=5)
g <- ggplot(pow, aes(delta, power)) +
  theme_classic() +
  geom_line(colour="red") +
  labs(x="Effect size", y="Power") +
  xlim(c(-6,6))
g

ggsave(paste0(fig, "t_power_5.png"), plot=g, device="png", width=3, height=3, dpi=300)
```


```{r plot_power_func}
plotPowerCurves <- function(pow, xlim=c(-6, 6)) {
  g <- ggplot(pow, aes(delta, power, group=n)) +
    theme_classic() +
    geom_line(aes(colour=n)) +
    labs(x="Effect size", y="Power") +
    xlim(xlim) +
    scale_colour_manual(values=cbPalette) +
    scale_y_continuous(breaks=seq(0,1,0.2)) +
    theme(legend.position = "none") +
    geom_hline(yintercept = 0.8, linetype="dashed")
  g
}

plotPowerSize <- function(pow) {
  g <- ggplot(pow, aes(n, delta, group=power)) +
    theme_classic() +
    geom_line(aes(colour=power)) +
    labs(x="Sample size", y="Effect size") +
    scale_colour_manual(values=cbPalette) +
    theme(legend.position = "none") +
    scale_x_log10(breaks=c(2,5,10,50))
  g
}
```


```{r t_power_curves, fig.width=3, fig.height=3}
pow <- tPowerCurve(n=c(2, 3, 5, 10, 30))
pow$n <- factor(pow$n, levels=c(2, 3, 5, 10, 30))

g <- plotPowerCurves(pow)
g 
 
ggsave(paste0(fig, "t_power_curves.png"), plot=g, device="png", width=3, height=3, dpi=300)

spow <- sPowerCurve(power=c(0.6, 0.8, 0.95))
spow$power <- factor(spow$power, levels=c(0.6, 0.8, 0.95))
g <- plotPowerSize(spow)
g
 
ggsave(paste0(fig, "t_size_curves.png"), plot=g, device="png", width=3, height=3, dpi=300)
```


```{r anova_power_curve_5}
anovaPowerCurve <- function(n=seq(2,10,1), f=seq(0, 10, 0.1), k=4) {
  D <- data.frame()
  for(i in n) {
    for(s in f) {
      D <- rbind(D, data.frame(
        n = i,
        delta = s,
        power = pwr.anova.test(n=i, k=k, f=s)$power
      ))
    }
  }
  D
}

anovaSizeCurve <- function(n=seq(2,50,1), power=c(0.6, 0.8, 0.95), k=4) {
  D <- data.frame()
  for(i in n) {
    for(p in power) {
      D <- rbind(D, data.frame(
        n = i,
        power = p,
        delta = pwr.anova.test(n=i, k=k, power=p)$f
      ))
    }
  }
  D
}
```


```{r anova_power_curves, fig.width=3, fig.height=3}
pow <- anovaPowerCurve(n=c(2, 3, 5, 10, 30))
pow$n <- factor(pow$n, levels=c(2, 3, 5, 10, 30))

g <- plotPowerCurves(pow, xlim=c(0,3))
g 
 
ggsave(paste0(fig, "anova_power_curves.png"), plot=g, device="png", width=3, height=3, dpi=300)

spow <- anovaSizeCurve(power=c(0.6, 0.8, 0.95))
spow$power <- factor(spow$power, levels=c(0.6, 0.8, 0.95))
g <- plotPowerSize(spow)
g

ggsave(paste0(fig, "anova_size_curves.png"), plot=g, device="png", width=3, height=3, dpi=300)
```

# New worked example

```{r generate_example_data}
set.seed(1002)
n <- 6
name <- c("WT", "KO1", "KO2", "KO3", "KO4")
M <- c(400, 400, 360, 200, 410)
S <- c(150, 150, 100, 140, 100)
P <- lapply(1:length(name), function(i) {
  repeat {
    x <- rnorm(n, M[i], S[i])
    if(all(x > 0)) break
  }
  data.frame(
    Group = name[i],
    Volume = x
  )
})
tumour <- do.call(rbind, P)
t.aov <- aov(Volume ~ Group, data=tumour)
summary(t.aov)

t2 <- subset(tumour, Group %in% c("WT", "KO3"))
t.test(Volume ~ Group, data=t2)
```

```{r tumour_plots, fig.width=4, fig.height=3}
g1 <- g <- ggplot(tumour, aes(x=Group, y=Volume)) +
    theme_classic() +
    theme(legend.position = "none") +
    geom_boxplot(aes(fill=Group), alpha=0.5, outlier.shape = NA) +
    scale_fill_manual(values=cbPalette) +
    geom_jitter(width=0.15, height=0) +
    labs(x="", y="Volume") +
    ylim(0, 600)
g1
ggsave(paste0(fig, "tumour_data.png"), plot=g1, device="png", width=3, height=3, dpi=300)


sdt <- tumour %>% group_by(Group) %>% summarise(sd=sd(Volume), n=n()) %>% mutate(sde=sd / sqrt(2*(n-1)))

g2 <- ggplot(sdt, aes(Group, sd)) +
  theme_classic() +
  geom_point() +
  geom_errorbar(aes(x=Group, ymin=sd-sde, ymax=sd+sde), width=0.2) +
  geom_hline(yintercept = c(75, 160), linetype="dotted") +
  labs(x="", y="Standard deviation")
g2
ggsave(paste0(fig, "tumour_sd.png"), plot=g2, device="png", width=3, height=3, dpi=300)
```


```{r tumour_case_1}
pow <- tPowerCurve(n=c(2, 3, 4, 5, 6, 10))
pow$n <- factor(pow$n)
g <- plotPowerCurves(pow, xlim=c(0, 6))

g <- g + geom_vline(xintercept = c(1.25, 2.7), linetype="dotted")

ggsave(paste0(fig, "tumour_power.png"), plot=g, device="png", width=3, height=3, dpi=300)
```


```{r tumour_t_power}
power.t.test(delta=200, sd=75, power=0.8)
power.t.test(delta=200, sd=160, power=0.8)
```

```{r tumour_anova_curves, fig.width=3, fig.height=3}
tum.aov = aov(Volume ~ Group, data=tumour)

# Extract F value
F = summary(tum.aov)[[1]]$F[1]

# Effect size: Cohen's f
f = sqrt((F - 1)/6)


pow <- anovaPowerCurve(n=c(2, 3, 4, 5, 6, 10), k=5)
pow$n <- factor(pow$n, levels=c(2, 3, 4, 5, 6, 10))

g <- plotPowerCurves(pow, xlim=c(0,2)) + geom_vline(xintercept = f, linetype="dotted")
g 

ggsave(paste0(fig, "tumour_anova.png"), plot=g, device="png", width=3, height=3, dpi=300)

```